---
apiVersion: 1
orgId: 1
folder: monitoring
name: monitoring
interval: 5m
rules:
  - uid: f6e55538-a3a3-4dd3-8308-19437ee8a58d
    title: Disk Space low
    for: 10m
    severity: medium
    summary: Disk space low on {{ $labels.mountpoint }} for {{ $labels.instance }}, {{ $values.B }} percent free
    condition: C
    annotations:
      execErrState: Error
      noDataState: NoData
    data:
      - refId: A
        expr: round((node_filesystem_avail_bytes / node_filesystem_size_bytes) * 100)
        intervalMs: 1000
        maxDataPoints: 43200
        datasourceUid: PBFA97CFB590B2093
        model:
          type: query
          conditions:
            - uid: __expr__
              type: reduce
              expression: A
              from: 600
              to: 0
              reducer: last
            - uid: __expr__
              expression: B
              from: 600
              to: 0
              reducer: last
            - uid: __expr__
              expression: C
              from: 600
              to: 0
              reducer: last
              type: threshold
        settings:
          legendFormat: __auto
          instant: true
          range: false
          relativeTimeRange:
            from: 600
            to: 0
