---
# Besu-specific verification tasks

# Check if besu container is running
- name: Check if besu container is running
  command: docker ps -q --filter "name=ephemery-besu"
  register: besu_container
  failed_when: besu_container.stdout == ""

# Check if besu is listening on the expected ports
- name: Check if besu HTTP API is accessible
  uri:
    url: http://localhost:8545
    method: POST
    body_format: json
    body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
    status_code: 200
  register: besu_api
  retries: 3
  delay: 5
  until: besu_api.status == 200
  ignore_errors: true

# Check besu metrics endpoint
- name: Check if besu metrics endpoint is accessible
  uri:
    url: http://localhost:9545/metrics
    method: GET
    status_code: 200
  register: besu_metrics
  retries: 3
  delay: 5
  until: besu_metrics.status == 200
  ignore_errors: true

# Check besu logs for errors
- name: Check besu logs
  command: docker logs ephemery-besu
  register: besu_logs
  changed_when: false
  failed_when: '"ERROR" in besu_logs.stdout or "FATAL" in besu_logs.stdout'
  ignore_errors: true
