---
# Geth-specific verification tasks

# Check if geth container is running
- name: Check if geth container is running
  command: docker ps -q --filter "name=ephemery-geth"
  register: geth_container
  failed_when: geth_container.stdout == ""

# Check if geth is listening on the expected ports
- name: Check if geth HTTP API is accessible
  uri:
    url: http://localhost:8545
    method: POST
    body_format: json
    body: '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":1}'
    status_code: 200
  register: geth_api
  retries: 3
  delay: 5
  until: geth_api.status == 200
  ignore_errors: true

# Check geth logs for errors
- name: Check geth logs
  command: docker logs ephemery-geth
  register: geth_logs
  changed_when: false
  failed_when:
    - '"ERROR" in geth_logs.stdout'
    - '"FATAL" in geth_logs.stdout'
  ignore_errors: true
