---
# Lighthouse-specific verification tasks

# Check if lighthouse beacon container is running
- name: Check if lighthouse beacon container is running
  command: docker ps -q --filter 'name=ephemery-lighthouse-beacon'
  register: lighthouse_beacon_container
  failed_when: lighthouse_beacon_container.stdout == ''

# Check if lighthouse is listening on the expected ports
- name: Check if lighthouse beacon API is accessible
  uri:
    url: http://localhost:5052/eth/v1/node/identity
    method: GET
    status_code: 200
  register: lighthouse_beacon_api
  retries: 3
  delay: 5
  until: lighthouse_beacon_api.status == 200
  ignore_errors: true

# Check lighthouse metrics endpoint
- name: Check if lighthouse metrics endpoint is accessible
  uri:
    url: http://localhost:5054/metrics
    method: GET
    status_code: 200
  register: lighthouse_metrics
  retries: 3
  delay: 5
  until: lighthouse_metrics.status == 200
  ignore_errors: true

# Check lighthouse logs for errors
- name: Check lighthouse beacon logs
  command: docker logs ephemery-lighthouse-beacon
  register: lighthouse_logs
  changed_when: false
  failed_when: '"ERROR" in lighthouse_logs.stdout or "FATAL" in lighthouse_logs.stdout'
  ignore_errors: true

# Check validator status (if enabled)
- name: Check if lighthouse validator container is running
  command: docker ps -q --filter 'name=ephemery-lighthouse-validator'
  register: lighthouse_validator_container
  when: validator_enabled | default(false) | bool
  failed_when: lighthouse_validator_container.stdout == '' and (validator_enabled | default(false) | bool)
  ignore_errors: true
