---
# Firewall rules for Erigon (execution client) and Prysm
# (consensus client) combination

firewall_allowed_tcp_ports:
  - 22      # SSH
  - 80      # HTTP
  - 443     # HTTPS
  - 30303   # Erigon P2P
  - 30304   # Erigon P2P
  - 8551    # Erigon Engine API
  - 13000   # Prysm P2P
  - 8080    # Prysm metrics

firewall_allowed_udp_ports:
  - 30303   # Erigon P2P
  - 30304   # Erigon P2P
  - 13000   # Prysm P2P
