---
# Pre-commit configuration for ansible-ephemery
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: mixed-line-ending
        args: [--fix=lf]

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.32.0
    hooks:
      - id: yamllint
        name: yamllint
        description: Lint YAML files with yamllint
        entry: yamllint -c .yamllint
        types: [yaml]
        args: [-f, parsable, --no-warnings]
        exclude: ^collections/

  - repo: local
    hooks:
      - id: check-yaml-extensions
        name: Check YAML file extensions
        entry: ./scripts/check-yaml-extensions.sh
        language: script
        pass_filenames: false
        types: [yaml]
        description: Checks that YAML files use the correct extension (.yaml except in molecule/ directory)
      - id: install-ansible-collections
        name: Install Ansible Collections
        entry: ./scripts/install-collections.sh
        language: script
        pass_filenames: false
        always_run: true
        stages: [pre-commit]
        description: Ensures that required Ansible collections are installed before linting
      - id: ansible-lint
        name: Ansible Lint
        description: Run ansible-lint on Ansible files
        entry: bash -c 'ANSIBLE_COLLECTIONS_PATH="$(git rev-parse --show-toplevel)/collections:$ANSIBLE_COLLECTIONS_PATH" ansible-lint --config-file .ansible-lint'
        language: system
        files: \.(yaml|yml)$
        additional_dependencies: []
        require_serial: true
        pass_filenames: false

  - repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        name: isort (python)
        args: [--profile black]

  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
      - id: black
        language_version: python3

  - repo: https://github.com/shellcheck-py/shellcheck-py
    rev: v0.9.0.5
    hooks:
      - id: shellcheck
        args: [--severity=warning]
