---
# Pre-commit hooks configuration for ansible-ephemery
# See https://pre-commit.com for more information

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-executables-have-shebangs
      - id: check-shebang-scripts-are-executable

  - repo: https://github.com/ansible-community/ansible-lint
    rev: v6.16.2
    hooks:
      - id: ansible-lint

  - repo: https://github.com/adrienverge/yamllint
    rev: v1.30.0
    hooks:
      - id: yamllint
        args:
          - --format
          - parsable
          - --strict

  # Custom hooks for enforcing Ansible Ephemery naming conventions
  - repo: local
    hooks:
      - id: enforce-task-naming
        name: Enforce task file naming conventions
        description: "Ensures task files use hyphens instead of underscores"
        entry: "python -c 'import sys, os, re; failed = False; filenames = sys.argv[1:]; [print(f\"ERROR: Task file {f} uses underscores instead of hyphens\") or (failed := True) for f in filenames if re.search(r\"tasks/.*_.*\\.yaml$\", f)]; sys.exit(1 if failed else 0)'"
        language: system
        files: 'tasks/.*_.*\.yaml$'
        exclude: '\.git/'
