---
# Main playbook for Ephemery node deployment

- name: Include required collections
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display collections
      ansible.builtin.debug:
        msg: 'Required collections have been included'

- name: Update Ephemery Nodes
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - defaults/main.yaml
    - vars/main.yaml
  tasks:
    - name: Load host-specific variables
      ansible.builtin.include_vars:
        file: 'ansible/host_vars/{{ inventory_hostname }}.yaml'

    - name: Pull latest execution client Docker image
      community.docker.docker_image:
        name: '{{ client_images[el] }}'
        source: pull
        force_source: false
      when: el is defined

    - name: Pull latest consensus client Docker image
      community.docker.docker_image:
        name: '{{ client_images[cl] }}'
        source: pull
        force_source: false
      when: cl is defined

    - name: Pull latest validator client Docker image (if enabled)
      community.docker.docker_image:
        name: '{{ client_images.validator }}'
        source: pull
        force_source: false
      when: validator_enabled | default(false) | bool

- name: 🏖️ Deploy Ephemery Nodes
  hosts: ephemery
  become: true
  vars:
    ephemery_base_dir: "/opt/ephemery"
    ephemery_dir: "{{ ephemery_base_dir }}"
    ephemery_scripts_dir: "{{ ephemery_base_dir }}/scripts"
    jwt_secret_path: "{{ ephemery_dir }}/jwt.hex"
  tasks:
    - name: 🏖️ Create cozy axolotl home directory 🏖️
      ansible.builtin.file:
        path: "{{ ephemery_base_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user | default('root') }}"
        group: "{{ ansible_user | default('root') }}"

    - name: Import main tasks
      ansible.builtin.import_tasks: ansible/tasks/main.yaml

- name: Configure Periodic Reset for Ephemery Nodes
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - defaults/main.yaml
    - vars/main.yaml
  tasks:
    - name: Load host-specific variables
      ansible.builtin.include_vars:
        file: 'ansible/host_vars/{{ inventory_hostname }}.yaml'

    - name: Setup periodic reset tasks
      ansible.builtin.import_tasks: ansible/tasks/periodic_reset.yaml
      when: ephemery_automatic_reset | default(false) | bool
