---
collections:
  - name: ansible.netcommon
    version: ">=2.5.0"
  - name: community.general
    version: ">=4.0.0"
  - name: community.docker
    version: ">=4.4.0"
  - name: ansible.posix
    version: ">=1.4.0"
  - name: ansible.utils
    version: ">=2.5.0"
