---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-ephemery role with resource limits
      include_role:
        name: ansible-ephemery
      vars:
        # Override variables for resource testing
        home_dir: /root
        # Set memory limits
        ephemery_docker_memory_limit: "3.6G"  # 90% of 4G
        el_memory_percentage: 0.6  # 60% for execution client
        cl_memory_percentage: 0.4  # 40% for consensus client

    # Wait for clients to initialize
    - name: Wait for clients to initialize
      pause:
        seconds: 30
