---
- name: Converge
  hosts: all
  tasks:
    - name: Include the role
      ansible.builtin.include_role:
        name: ../../ansible
      vars:
        el_memory_limit: 2048M
        cl_memory_limit: 1024M

    # Wait for clients to initialize
    - name: Wait for clients to initialize
      pause:
        seconds: 30
