---
# Handlers for ansible-ephemery

- name: Display password file copied
  ansible.builtin.debug:
    msg: 'Password file copied to {{ ephemery_base_dir }}/secrets/validator/passwords/validators.txt'
  listen: Display password file copied

- name: Extract Ephemery network configuration
  ansible.builtin.unarchive:
    src: '{{ ephemery_dir }}/config/ephemery_network/testnet-all.tar.gz'
    dest: '{{ ephemery_dir }}/config/ephemery_network/'
    remote_src: true
    owner: '{{ ansible_user | default("root") }}'
    group: '{{ ansible_user | default("root") }}'
    mode: '0644'
