---
- name: Ensure ephemery directory exists
  ansible.builtin.file:
    path: "{{ ephemery_base_dir }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Check if secure JWT generation is enabled
  ansible.builtin.set_fact:
    use_vault: "{{ jwt_secret_secure_generation| default(false) }}"

# Standard JWT secret generation (less secure)
- name: Generate JWT secret with openssl if not using vault
  ansible.builtin.shell: |
    if [ ! -f {{ jwt_secret_path }} ]; then
      echo -n 0x$(openssl rand -hex 32 | tr -d "\n") > {{ jwt_secret_path }}
      chmod 600 {{ jwt_secret_path }}
    fi
  args:
    creates: "{{ jwt_secret_path }}"
  when: not use_vault

# Secure JWT secret generation (using ansible-vault)
- block:
  - name: Ensure templates directory exists
    ansible.builtin.file:
      path: templates
      state: directory
      mode: '0755'
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"

  - name: Check if jwt_secret template exists
    ansible.builtin.stat:
      path: templates/jwt_secret.j2
    register: jwt_template

  - name: Create jwt_secret template if it doesn't exist
    ansible.builtin.shell: |
      echo "{{ '0x' + lookup('password', '/dev/null chars=hexdigits length=64') }}" > templates/jwt_secret.j2
      chmod 600 templates/jwt_secret.j2
    when: not jwt_template.stat.exists

  - name: Encrypt the JWT secret template with ansible-vault if not already encrypted
    ansible.builtin.shell: |
      if ! grep -q "\$ANSIBLE_VAULT;" templates/jwt_secret.j2; then
        ansible-vault encrypt templates/jwt_secret.j2
      fi
    args:
      executable: /bin/bash

  - name: Deploy JWT secret using template and vault
    ansible.builtin.template:
      src: templates/jwt_secret.j2
      dest: "{{ jwt_secret_path }}"
      owner: "{{ ansible_user }}"
      group: "{{ ansible_user }}"
      mode: '0600'
  when: use_vault

- name: Ensure JWT secret has proper permissions
  ansible.builtin.file:
    path: "{{ jwt_secret_path }}"
    mode: '0600'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
