---
# Firewall rules for Nethermind (execution client) and Lodestar
# (consensus client) combination

firewall_allowed_tcp_ports:
  - 22      # SSH
  - 80      # HTTP
  - 443     # HTTPS
  - 30303   # Nethermind P2P
  - 8551    # Nethermind Engine API
  - 9000    # Lodestar P2P
  - 8008    # Lodestar metrics

firewall_allowed_udp_ports:
  - 30303   # Nethermind P2P
  - 9000    # Lodestar P2P
