---
# Example host-specific variables
# IMPORTANT: This is an example file. Copy to a real host file and customize as needed.

# Base directory configuration
# Use ephemery_base_dir rather than ephemery_dir in new configurations
ephemery_base_dir: /opt/ephemery
# The following is kept for backward compatibility but should be avoided in new configurations
ephemery_dir: "{{ ephemery_base_dir }}"
ephemery_data_dir: "{{ ephemery_base_dir }}/data"
ephemery_scripts_dir: "{{ ephemery_base_dir }}/scripts"
ephemery_secrets_dir: "{{ ephemery_base_dir }}/secrets"
ephemery_logs_dir: "{{ ephemery_base_dir }}/logs"
ephemery_backup_dir: "{{ ephemery_base_dir }}/backups"

# JWT Secret configuration
# IMPORTANT: Always use the standard path and filename for JWT secrets
# The jwt.hex file should be used consistently across all client configurations
jwt_secret_path: "{{ ephemery_base_dir }}/jwt.hex"
jwt_secret_secure_generation: true

# Client selection
el: geth
cl: lighthouse
use_checkpoint_sync: true
clear_database: false

# Client specific variables
cl_client_name: lighthouse
cl_client_port: 5052
cl_p2p_port: 9000
cl_metrics_port: 5054

# Validator configuration
validator_enabled: false
validator_keys_dir: "{{ ephemery_base_dir }}/validator_keys"
validator_keys_password_file: "files/passwords/validators.txt"

# Monitoring and resource configuration
monitoring_enabled: true
prometheus_enabled: true
grafana_enabled: true
cadvisor_enabled: true
grafana_port: 3000
prometheus_port: 9090

# SENSITIVE VALUES
# IMPORTANT: The values below should be encrypted with ansible-vault in production
# Example encrypt command: ansible-vault encrypt_string --name 'telegram_bot_token' 'your_token_here'
# You should see !vault | followed by encrypted content instead of plain text
# See docs/SECRET_MANAGEMENT.md for more information

# Example encrypted values (replace with actual encrypted values):
# grafana_admin_password: !vault |
#   $ANSIBLE_VAULT;1.1;AES256
#   31613262303566333532343865346138663439343862623239613233653264323166333130396333
#   3161313661666464636262333762386139346562656632390a323031616630616535383333353030
#   63323763623132323038646663656661633732383435343431346664303464643436393635636235
#   3430353366383932340a326664396534623565343461653034363032313335363738633536643966
#   3461

# Example cleartext values (ONLY FOR DEVELOPMENT - ENCRYPT IN PRODUCTION)
# For testing in development environments only:
grafana_admin_password: "admin"

# Connection settings
ansible_host: example-server.example.com
ansible_user: ubuntu
ip: 192.168.1.10
