---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if required services are running
      ansible.builtin.service_facts:

    - name: Assert monitoring services are running
      ansible.builtin.assert:
        that: ansible_facts.services['{{ item }}'].state == 'running'
        fail_msg: "Required service {{ item }} is not running"
        success_msg: "Service {{ item }} is running correctly"
      loop:
        - prometheus
        - grafana-server
        - cadvisor
        - node_exporter
      ignore_errors: true

    - name: Verify monitoring ports are open
      ansible.builtin.command: "ss -tulpn | grep {{ item.port }}"
      register: port_check
      changed_when: false
      failed_when: false
      loop:
        - { service: "prometheus", port: "9090" }
        - { service: "grafana", port: "3000" }
        - { service: "cadvisor", port: "8080" }
        - { service: "node-exporter", port: "9100" }

    - name: Assert monitoring ports are open
      ansible.builtin.assert:
        that: item.stdout != ""
        fail_msg: "{{ item.item.service }} port {{ item.item.port }} is not open"
        success_msg: "{{ item.item.service }} port {{ item.item.port }} is open"
      loop: "{{ port_check.results }}"
      ignore_errors: true
