---
# Directory setup tasks for common role

- name: Determine common directories
  ansible.builtin.set_fact:
    common_directories:
      - "{{ data_dir }}"
      - "{{ log_dir }}"
      - "{{ config_dir }}"
      - "{{ scripts_dir }}"
      - "{{ data_dir }}/execution"
      - "{{ data_dir }}/consensus"
      - "{{ data_dir }}/validator"
      - "{{ data_dir }}/jwt"
      - "{{ data_dir }}/backup"
      - "{{ data_dir }}/monitoring"

- name: Create common directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    mode: '0755'
  with_items: "{{ common_directories }}"
  become: true

- name: Set secure permissions for sensitive directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    mode: '0700'
  with_items:
    - "{{ data_dir }}/jwt"
    - "{{ data_dir }}/validator"
  become: true

- name: Create symlinks for legacy directory paths
  when: jwt_create_symlinks | bool
  block:
    - name: Set legacy directory paths
      ansible.builtin.set_fact:
        legacy_directories:
          - path: "/var/lib/ethereum"
            target: "{{ data_dir }}"
          - path: "/etc/ethereum"
            target: "{{ config_dir }}"

    - name: Ensure parent directories exist for symlinks
      ansible.builtin.file:
        path: "{{ item.path | dirname }}"
        state: directory
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        mode: '0755'
      with_items: "{{ legacy_directories }}"
      become: true

    - name: Create symlinks for legacy directories
      ansible.builtin.file:
        src: "{{ item.target }}"
        dest: "{{ item.path }}"
        state: link
        owner: "{{ common_user }}"
        group: "{{ common_group }}"
        force: true
      with_items: "{{ legacy_directories }}"
      become: true
