---
# Docker installation tasks for common role

- name: Install dependencies for Docker repository
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - lsb-release
    state: present
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add Docker GPG key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add Docker repository
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install Docker packages
  apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
    state: present
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu"
  register: docker_install

- name: Enable and start Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Create Docker group if it does not exist
  group:
    name: docker
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add user to Docker group
  user:
    name: "{{ common_user }}"
    groups: docker
    append: yes
  become: true
  register: docker_user
  when: ansible_distribution == "Ubuntu"

- name: Install Docker Compose
  get_url:
    url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-Linux-x86_64"
    dest: /usr/local/bin/docker-compose
    mode: '0755'
  become: true
  when: docker_compose_install | bool

- name: Check Docker Compose version
  command: docker-compose --version
  register: docker_compose_version_output
  changed_when: false
  failed_when: false
