---
# Main tasks file for the common role

- name: Include OS-specific variables
  include_vars: "{{ item }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
    - "default.yml"
  tags: always

- name: Setup directories
  include_tasks: directories.yml
  tags:
    - directories
    - common

- name: Setup system requirements
  include_tasks: system_setup.yml
  tags:
    - system
    - common

- name: Configure user and group
  include_tasks: user.yml
  when: create_common_user | bool
  tags:
    - user
    - common

- name: Setup JWT secret
  include_tasks: jwt_management.yml
  tags:
    - jwt
    - common

- name: Configure firewall
  include_tasks: firewall.yml
  when: configure_firewall | bool
  tags:
    - firewall
    - common

- name: Setup Docker
  include_tasks: docker.yml
  when: docker_install | bool
  tags:
    - docker
    - common

- name: Setup monitoring prerequisites
  include_tasks: monitoring.yml
  when: enable_monitoring | bool
  tags:
    - monitoring
    - common

- name: Apply security configurations
  include_tasks: security.yml
  when: enable_security | default(true) | bool
  tags:
    - security
    - common

- name: Apply system performance tuning
  include_tasks: system_tuning.yml
  when: enable_tuning | default(true) | bool
  tags:
    - tuning
    - performance
    - common
