---
# System tuning tasks for the common role

##############################################################################
# CPU PERFORMANCE TUNING
##############################################################################

- name: Check if tuned is installed
  package:
    name: tuned
    state: present
  become: true
  tags:
    - tuning
    - performance

- name: Create tuned profile directory for Ethereum nodes
  file:
    path: /etc/tuned/ethereum-node
    state: directory
    mode: '0755'
  become: true
  tags:
    - tuning
    - performance

- name: Create Ethereum node tuned profile
  template:
    src: tuned/ethereum-node-profile.conf.j2
    dest: /etc/tuned/ethereum-node/tuned.conf
    mode: '0644'
  become: true
  tags:
    - tuning
    - performance

- name: Enable tuned service
  service:
    name: tuned
    state: started
    enabled: yes
  become: true
  tags:
    - tuning
    - performance

- name: Apply Ethereum node tuned profile
  command: tuned-adm profile ethereum-node
  become: true
  tags:
    - tuning
    - performance

##############################################################################
# MEMORY OPTIMIZATION
##############################################################################

- name: Configure swappiness
  sysctl:
    name: vm.swappiness
    value: '10'
    state: present
    sysctl_set: yes
    reload: yes
  become: true
  tags:
    - tuning
    - memory

- name: Configure cache pressure
  sysctl:
    name: vm.vfs_cache_pressure
    value: '50'
    state: present
    sysctl_set: yes
    reload: yes
  become: true
  tags:
    - tuning
    - memory

- name: Configure dirty ratio
  sysctl:
    name: vm.dirty_ratio
    value: '10'
    state: present
    sysctl_set: yes
    reload: yes
  become: true
  tags:
    - tuning
    - memory

- name: Configure dirty background ratio
  sysctl:
    name: vm.dirty_background_ratio
    value: '5'
    state: present
    sysctl_set: yes
    reload: yes
  become: true
  tags:
    - tuning
    - memory

##############################################################################
# DISK I/O OPTIMIZATION
##############################################################################

- name: Install I/O scheduler tool
  package:
    name: util-linux
    state: present
  become: true
  tags:
    - tuning
    - disk

- name: Get block devices
  shell: lsblk -dn | awk '{print $1}' | grep -v 'loop'
  register: block_devices
  changed_when: false
  become: true
  tags:
    - tuning
    - disk

- name: Check if I/O scheduler is configurable
  stat:
    path: "/sys/block/{{ item }}/queue/scheduler"
  with_items: "{{ block_devices.stdout_lines }}"
  register: scheduler_check
  become: true
  tags:
    - tuning
    - disk

- name: Set I/O scheduler to deadline for SSDs
  shell: echo deadline > /sys/block/{{ item.item }}/queue/scheduler
  when:
    - item.stat.exists
    - system_disks_are_ssd | default(true)
  with_items: "{{ scheduler_check.results }}"
  become: true
  tags:
    - tuning
    - disk

- name: Optimize read-ahead for Ethereum workloads
  shell: blockdev --setra 1024 /dev/{{ item.item }}
  with_items: "{{ scheduler_check.results }}"
  when: item.stat.exists
  become: true
  tags:
    - tuning
    - disk

##############################################################################
# NETWORK TUNING
##############################################################################

- name: Optimize network settings for Ethereum node
  sysctl:
    name: "{{ item.key }}"
    value: "{{ item.value }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_dict:
    net.core.rmem_max: 16777216
    net.core.wmem_max: 16777216
    net.core.rmem_default: 262144
    net.core.wmem_default: 262144
    net.ipv4.tcp_rmem: "4096 87380 16777216"
    net.ipv4.tcp_wmem: "4096 65536 16777216"
    net.ipv4.tcp_slow_start_after_idle: 0
    net.ipv4.tcp_fastopen: 3
    net.ipv4.tcp_mtu_probing: 1
  become: true
  tags:
    - tuning
    - network
