---
# Directory setup tasks for consensus_client role

- name: Determine consensus client directories
  set_fact:
    consensus_directories:
      - "{{ cl_data_dir }}"
      - "{{ cl_log_dir }}"
      - "{{ lighthouse_data_dir }}"
      - "{{ prysm_data_dir }}"
      - "{{ teku_data_dir }}"
      - "{{ nimbus_data_dir }}"
      - "{{ lodestar_data_dir }}"
      - "{{ config_dir }}/consensus"

- name: Create consensus client directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    mode: '0755'
  with_items: "{{ consensus_directories }}"
  become: true

- name: Create client-specific directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    mode: '0755'
  with_items:
    - "{{ cl_data_dir }}/{{ cl_client_name }}"
  become: true

- name: Create symlink for client data directory
  file:
    src: "{{ cl_data_dir }}/{{ cl_client_name }}"
    dest: "{{ cl_data_dir }}/current"
    state: link
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    force: true
  become: true
