---
# Lighthouse-specific tasks for the consensus_client role

- name: Add Lighthouse repository signing key
  apt_key:
    url: https://github.com/sigp/lighthouse-signing-key/raw/main/signing-key.asc
    state: present
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Add Lighthouse repository
  apt_repository:
    repo: deb [arch=amd64] https://lighthouse-metrics.sigp.io/apt {{ ansible_distribution_release }} main
    state: present
    update_cache: yes
  become: true
  when: ansible_distribution == "Ubuntu"

- name: Install Lighthouse
  package:
    name: lighthouse
    state: present
  become: true
  register: lighthouse_install

- name: Get Lighthouse version
  command: lighthouse --version
  register: lighthouse_version_output
  changed_when: false

- name: Display Lighthouse version
  debug:
    msg: "Installed Lighthouse version: {{ lighthouse_version_output.stdout.split(' ')[1] | default('unknown') }}"

- name: Create Lighthouse data directory
  file:
    path: "{{ lighthouse_data_dir }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    mode: '0755'
  become: true

- name: Create Lighthouse log directory
  file:
    path: "{{ cl_log_dir }}"
    state: directory
    owner: "{{ common_user }}"
    group: "{{ common_group }}"
    mode: '0755'
  become: true

- name: Create Lighthouse systemd service
  template:
    src: lighthouse.service.j2
    dest: /etc/systemd/system/lighthouse.service
    owner: root
    group: root
    mode: '0644'
  become: true
  register: lighthouse_service
  notify: restart lighthouse

- name: Reload systemd daemon
  systemd:
    daemon_reload: yes
  become: true
  when: lighthouse_service.changed

- name: Enable and start Lighthouse service
  systemd:
    name: lighthouse
    enabled: yes
    state: started
  become: true
  when: cl_service_enabled | bool 