---
# Main tasks file for the consensus_client role

- name: Set up consensus client directories
  include_tasks: directories.yml
  tags:
    - consensus
    - directories

- name: Install consensus client
  block:
    - name: Include client-specific tasks - Lighthouse
      include_tasks: lighthouse.yml
      when: cl_client_name == "lighthouse"
      tags:
        - consensus
        - lighthouse

    - name: Include client-specific tasks - Prysm
      include_tasks: prysm.yml
      when: cl_client_name == "prysm"
      tags:
        - consensus
        - prysm

    - name: Include client-specific tasks - Teku
      include_tasks: teku.yml
      when: cl_client_name == "teku"
      tags:
        - consensus
        - teku

    - name: Include client-specific tasks - Nimbus
      include_tasks: nimbus.yml
      when: cl_client_name == "nimbus"
      tags:
        - consensus
        - nimbus

    - name: Include client-specific tasks - Lodestar
      include_tasks: lodestar.yml
      when: cl_client_name == "lodestar"
      tags:
        - consensus
        - lodestar
  tags:
    - consensus

- name: Set up consensus client service
  include_tasks: service.yml
  tags:
    - consensus
    - services
