---
# Main tasks for consensus client role

- name: Include client-specific configuration
  ansible.builtin.include_tasks: "{{ cl_client_name }}.yaml"
  when: cl_client_name is defined

- name: Create consensus client data directory
  ansible.builtin.file:
    path: "{{ cl_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user | default('root') }}"
    group: "{{ ansible_user | default('root') }}"

- name: Setup docker network if needed
  community.docker.docker_network:
    name: "{{ cl_container_network }}"
    state: present
  when: create_network | default(true) | bool

- name: Pull consensus client docker image
  community.docker.docker_image:
    name: "{{ cl_client_image }}"
    source: pull
    force_source: "{{ force_image_update | default(false) | bool }}"

- name: Setup consensus client container
  community.docker.docker_container:
    name: "{{ cl_container_name }}"
    image: "{{ cl_client_image }}"
    restart_policy: "{{ cl_restart_policy }}"
    network_mode: "{{ cl_container_network }}"
    volumes:
      - "{{ cl_data_dir }}:/data"
      - "{{ jwt_secret_path }}:/jwtsecret"
    ports:
      - "{{ cl_client_port }}:{{ cl_client_port }}"
      - "{{ cl_p2p_port }}:{{ cl_p2p_port }}/tcp"
      - "{{ cl_p2p_port }}:{{ cl_p2p_port }}/udp"
      - "{{ cl_metrics_port }}:{{ cl_metrics_port }}"
    command: "{{ cl_container_command }}"
    env: "{{ cl_container_env | default({}) }}"
    state: started 