---
# Service tasks for consensus_client role

- name: Check if consensus client service is running
  systemd:
    name: "{{ cl_client_name }}"
  register: cl_service_status
  failed_when: false
  ignore_errors: true
  become: true

- name: Display consensus client service status
  debug:
    msg: "{{ cl_client_name }} service status: {{ cl_service_status.status | default('not installed') }}"

- name: Wait for consensus client to start (if already running)
  uri:
    url: "http://localhost:{{ cl_http_port }}/eth/v1/node/version"
    method: GET
    status_code: 200
  register: cl_api_check
  until: cl_api_check.status == 200
  retries: 3
  delay: 5
  failed_when: false
  when:
    - cl_service_status.status is defined
    - cl_service_status.status == "running"
    - cl_http_enabled | bool

- name: Display API connectivity status
  debug:
    msg: "{{ cl_client_name }} API connectivity: {{ 'OK' if cl_api_check.status is defined and cl_api_check.status == 200 else 'Not available' }}"
  when: cl_http_enabled | bool
