---
- name: Converge
  hosts: all
  tasks:
    - name: Debug - Show variables
      ansible.builtin.debug:
        msg: |
          Test Mode: {{ test_mode | default('undefined') }}
          Validator Enabled: {{ validator_enabled | default('undefined') }}
          Home Directory: {{ home_dir | default('undefined') }}
          Ephemery Base Directory: {{ ephemery_base_dir | default('undefined') }}
          Ansible User: {{ ansible_user | default('undefined') }}

    - name: Include the role
      ansible.builtin.include_role:
        name: ../../ansible
      vars:
        test_mode: true
        validator_enabled: true
        # Override variables for testing validators
        home_dir: /root
        ephemery_base_dir: '{{ home_dir }}/ephemery'
        ephemery_dir: '{{ ephemery_base_dir }}'
        ephemery_data_dir: '{{ ephemery_base_dir }}/data'
        ephemery_secrets_dir: '{{ ephemery_base_dir }}/secrets'
        # Validator-specific test variables
        validator_memory_limit: 1024M
        validator_client: '{{ cl }}'
