---
- name: Verify
  hosts: all
  gather_facts: false
  vars:
    test_mode: true
  tasks:
    - name: Check if required services are running
      ansible.builtin.service_facts:

    - name: Get systemd services
      ansible.builtin.command: systemctl list-units --type=service --all
      register: systemd_services
      changed_when: false

    - name: Debug systemd services
      ansible.builtin.debug:
        var: systemd_services.stdout_lines

    - name: Verify validator configuration files
      ansible.builtin.stat:
        path: "{{ item }}"
      register: validator_files
      loop:
        - /etc/ethereum/validators
        - /etc/systemd/system/validator.service
      when: not test_mode | default(false) | bool

    - name: Assert validator files exist
      ansible.builtin.assert:
        that:
          - item.stat.exists
        fail_msg: "Required validator file {{ item.item }} does not exist"
        success_msg: "Validator file {{ item.item }} exists"
      loop: "{{ validator_files.results }}"
      when: not test_mode | default(false) | bool
