---
- name: Verify validator functionality
  hosts: all
  become: true
  vars:
    validator_enabled: true
  tasks:
    # Include common verification tasks
    - name: Include common verification tasks
      ansible.builtin.include_tasks: ../shared/templates/verify/common.yml

    # Include validator-specific verification tasks
    - name: Include validator-specific verification tasks
      ansible.builtin.include_tasks: ../shared/templates/verify/validator.yml

    # Additional validator-specific verification tasks
    - name: Verify validator API is responding
      uri:
        url: http://localhost:5064/metrics
        method: GET
        status_code: 200
      register: validator_metrics
      failed_when: false
      changed_when: false
      when: validator_enabled | bool and not is_molecule_test | bool

    - name: Assert validator API is responding if enabled
      assert:
        that: validator_metrics.status == 200
        fail_msg: Validator API is not responding at http://localhost:5064/metrics
        success_msg: Validator API is responding correctly
      when: validator_enabled | bool and not is_molecule_test | bool and validator_metrics.status is defined
