---
- name: Check if client combination is selected

  ansible.builtin.set_fact:
    client_skip: '{{ not (el == "geth" and cl == "prysm") }}'

- name: 🌟 Ensure client directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop:
    - '{{ ephemery_data_dir }}/el'
    - '{{ ephemery_data_dir }}/cl'
    - '{{ ephemery_logs_dir }}'
  when: not client_skip

- name: 🔑 Ensure JWT secret exists
  ansible.builtin.import_tasks:
    file: tasks/jwt-secret.yaml
  when: not client_skip

- name: 🚀 Start Geth (Execution Client)
  community.docker.docker_container:
    name: '{{ network }}-geth'
    image: 'pk910/ephemery-geth:v1.15.3'
    state: started
    pull: true
    restart_policy: unless-stopped
    network_mode: host
    memory: '{{ el_memory_limit }}'
    volumes:
      - '{{ jwt_secret_path }}:/execution-auth.jwt:ro'
      - '{{ ephemery_data_dir }}/el:/data'
    command: >
      --datadir=/data
      --http
      --http.addr=0.0.0.0
      --http.api=engine,eth,web3,net
      --http.port=8545
      --http.vhosts=*
      --ws
      --ws.addr=0.0.0.0
      --ws.origins=*
      --ws.api=engine,eth,web3,net
      --ws.port=8546
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
      --authrpc.jwtsecret=/execution-auth.jwt
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.vhosts=*
  when: not client_skip

- name: 🚀 Start Prysm (Consensus Client)
  community.docker.docker_container:
    name: '{{ network }}-prysm'
    image: 'pk910/ephemery-prysm:v4.1.1'
    state: started
    pull: true
    restart_policy: unless-stopped
    network_mode: host
    memory: '{{ cl_memory_limit }}'
    volumes:
      - '{{ jwt_secret_path }}:/execution-auth.jwt:ro'
      - '{{ ephemery_data_dir }}/cl:/data'
    command: >
      --datadir=/data
      --ephemery-network
      --accept-terms-of-use
      --rpc-host=0.0.0.0
      --rpc-port=3500
      --grpc-gateway-host=0.0.0.0
      --grpc-gateway-port=3501
      --monitoring-host=0.0.0.0
      --monitoring-port=9999
      --p2p-tcp-port=9001
      --p2p-udp-port=9001
      --execution-endpoint=http://127.0.0.1:8551
      --jwt-secret=/execution-auth.jwt
      --disable-blst
  when: not client_skip
