---
- name: Check if client combination is selected

  ansible.builtin.set_fact:
    client_skip: '{{ not (el == "erigon" and cl == "lodestar") }}'

- name: 🌟 Ensure client directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop:
    - '{{ ephemery_data_dir }}/el'
    - '{{ ephemery_data_dir }}/cl'
    - '{{ ephemery_logs_dir }}'
  when: not client_skip

- name: 🔑 Ensure JWT secret exists
  ansible.builtin.import_tasks:
    file: tasks/jwt-secret.yaml
  when: not client_skip

- name: 🚀 Start Erigon (Execution Client)
  community.docker.docker_container:
    name: '{{ network }}-erigon'
    image: 'pk910/ephemery-erigon:v2.55.1'
    state: started
    pull: true
    restart_policy: unless-stopped
    network_mode: host
    memory: '{{ el_memory_limit }}'
    volumes:
      - '{{ jwt_secret_path }}:/execution-auth.jwt:ro'
      - '{{ ephemery_data_dir }}/el:/data'
    command: >
      --datadir=/data
      --http
      --http.addr=0.0.0.0
      --http.port=8545
      --http.api=eth,erigon,web3,net,debug,trace,txpool
      --ws
      --private.api.addr=0.0.0.0:9090
      --metrics
      --metrics.addr=0.0.0.0
      --metrics.port=6060
      --authrpc.addr=0.0.0.0
      --authrpc.port=8551
      --authrpc.jwtsecret=/execution-auth.jwt
      --p2p.allowed-ports=30303,30304
  when: not client_skip

- name: 🚀 Start Lodestar (Consensus Client)
  community.docker.docker_container:
    name: '{{ network }}-lodestar'
    image: 'pk910/ephemery-lodestar:v1.13.0'
    state: started
    pull: true
    restart_policy: unless-stopped
    network_mode: host
    memory: '{{ cl_memory_limit }}'
    volumes:
      - '{{ jwt_secret_path }}:/execution-auth.jwt:ro'
      - '{{ ephemery_data_dir }}/cl:/data'
    command: >
      beacon
      --dataDir=/data
      --ephemery-network
      --execution.urls=http://127.0.0.1:8551
      --jwt-secret=/execution-auth.jwt
      --rest.address=0.0.0.0
      --rest.port=5052
      --metrics.enabled=true
      --metrics.address=0.0.0.0
      --metrics.port=9000
  when: not client_skip
