---
- name: Verify security configurations
  hosts: all
  become: true
  tasks:
    - name: Check JWT secret file permissions
      stat:
        path: "{{ jwt_secret_path }}"
      register: jwt_file
      failed_when:
        - not jwt_file.stat.exists
        - jwt_file.stat.mode != '0600'  # Should be readable only by owner

    - name: Check if firewall is enabled
      command: ufw status
      register: firewall_status
      changed_when: false
      failed_when: firewall_enabled and "inactive" in firewall_status.stdout
      ignore_errors: true  # May fail on non-Ubuntu systems

    - name: Check alternative firewall (firewalld)
      command: firewall-cmd --state
      register: firewalld_status
      changed_when: false
      failed_when: firewall_enabled and "running" not in firewalld_status.stdout
      ignore_errors: true  # May fail on non-RedHat systems

    - name: Verify required ports are open in UFW
      command: ufw status
      register: ufw_ports
      changed_when: false
      failed_when: >
        firewall_enabled and
        ("{{ item }}/tcp" not in ufw_ports.stdout)
      loop: "{{ firewall_allowed_tcp_ports }}"
      ignore_errors: true  # May fail on non-Ubuntu systems

    - name: Verify Docker socket permissions
      stat:
        path: /var/run/docker.sock
      register: docker_sock
      failed_when:
        - docker_sock.stat.exists
        - docker_sock.stat.mode not in ['0660', '0666']  # Should be group readable

    - name: Check for exposed sensitive ports
      command: ss -tulpn
      register: open_ports
      changed_when: false
      failed_when: >
        "0.0.0.0:{{ item }}" in open_ports.stdout or
        ":::{{ item }}" in open_ports.stdout
      loop:
        - 8545  # Should only listen on localhost
        - 8551  # Engine API should be restricted
      ignore_errors: true
