---
- name: Converge
  hosts: all
  tasks:
    - name: Include the role
      ansible.builtin.include_role:
        name: ansible
      vars:
        backup_enabled: true

    # Create some fake data for backup testing
    - name: Create test data for backup
      copy:
        content: Test data for backup '{{ ansible_date_time.iso8601 }}'
        dest: /root/ephemery/data/el/testdata.txt

    # Run backup script manually to test functionality
    - name: Execute backup script for testing
      ansible.builtin.command: /root/ephemery/scripts/backup.sh
      changed_when: true
