---
# Backup scenario configuration
# Imports base configuration from shared/base_molecule.yml

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: "geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible:latest"
    command: ""
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
  inventory:
    host_vars:
      ethereum-node:
        # Only specify values that differ from shared host_vars
        el: geth
        cl: lighthouse
        validator_enabled: false
        backup_enabled: true
        firewall_enabled: false
        # Backup specific settings with namespaced variables
        backup_frequency: "daily"
        backup_retention_days: 7
        backup_compression_level: 6  # Override default
verifier:
  name: ansible
