---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:
    - name: Check if backup scripts are installed
      ansible.builtin.stat:
        path: "{{ item }}"
      register: backup_files
      loop:
        - /etc/cron.daily/backup-ethereum
        - /usr/local/bin/backup-ethereum.sh

    - name: Assert backup files exist
      ansible.builtin.assert:
        that: item.stat.exists
        fail_msg: "Backup file {{ item.item }} does not exist"
        success_msg: "Backup file {{ item.item }} exists"
      loop: "{{ backup_files.results }}"

    - name: Check if backup directory exists
      ansible.builtin.stat:
        path: /root/ephemery/backups
      register: backup_dir

    - name: Assert backup directory exists
      ansible.builtin.assert:
        that: backup_dir.stat.exists and backup_dir.stat.isdir
        fail_msg: "Backup directory does not exist or is not a directory"
        success_msg: "Backup directory exists"

    - name: Run backup script manually
      ansible.builtin.command: /usr/local/bin/backup-ethereum.sh
      changed_when: true
      register: backup_result

    - name: Check if backups were created
      ansible.builtin.find:
        paths: /root/ephemery/backups
        patterns: "*.tar.gz"
      register: backup_files_result

    - name: Assert backup files were created
      ansible.builtin.assert:
        that: backup_files_result.matched > 0
        fail_msg: "No backup files were created"
        success_msg: "{{ backup_files_result.matched }} backup files were created"
