---
# Common variables for all hosts
# These settings apply to all hosts in the inventory

# Global network settings
ephemery_network: true
docker_installed: true

# SSH Connection settings
ansible_become: true
ansible_ssh_pipelining: true
ansible_ssh_keepalive: true

# These variables should be provided in inventory or host_vars
# ansible_user: "root"
# ansible_ssh_private_key_file: "/path/to/private/key"
# ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
# ansible_ssh_extra_args: ""
