---
# Service tasks for execution_client role

- name: Check if execution client service is running
  systemd:
    name: "{{ el_client_name }}"
  register: el_service_status
  failed_when: false
  ignore_errors: true
  become: true

- name: Display execution client service status
  debug:
    msg: "{{ el_client_name }} service status: {{ el_service_status.status | default('not installed') }}"

- name: Wait for execution client to start (if already running)
  uri:
    url: "http://localhost:{{ el_http_port }}"
    method: POST
    body_format: json
    body: '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}'
    status_code: 200
  register: el_rpc_check
  until: el_rpc_check.status == 200
  retries: 3
  delay: 5
  failed_when: false
  when: 
    - el_service_status.status is defined
    - el_service_status.status == "running"
    - el_http_enabled | bool

- name: Display RPC connectivity status
  debug:
    msg: "{{ el_client_name }} RPC connectivity: {{ 'OK' if el_rpc_check.status is defined and el_rpc_check.status == 200 else 'Not available' }}"
  when: el_http_enabled | bool 