---
# Base host variables for ethereum-node
# Individual scenarios can override these values
network: ephemery
ephemery_base_dir: /home/ubuntu/ephemery
ephemery_data_dir: /home/ubuntu/ephemery/data
ephemery_logs_dir: /home/ubuntu/ephemery/logs
ephemery_scripts_dir: /home/ubuntu/ephemery/scripts
ephemery_backup_dir: /home/ubuntu/ephemery/backups
jwt_secret_path: /home/ubuntu/ephemery/jwtsecret
validator_enabled: false
backup_enabled: true
firewall_enabled: true
prometheus_port: 9090
grafana_port: 3000
grafana_agent_http_port: 12345
cadvisor_port: 8080
el_memory_limit: 2048M
cl_memory_limit: 2048M

# Default clients
el: geth
cl: lighthouse
