---
# Task to ensure genesis sync is used everywhere for Ephemery nodes

- name: Set default network name
  ansible.builtin.set_fact:
    default_network: "ephemery"
  when: network is not defined

- name: Update host vars to use genesis sync
  ansible.builtin.lineinfile:
    path: "{{ inventory_dir }}/host_vars/{{ item }}.yaml"
    regexp: "use_checkpoint_sync: true"
    line: "use_checkpoint_sync: false"
    state: present
    backup: yes
  become: false
  delegate_to: localhost
  with_items: "{{ groups['all'] | default([]) }}"
  when:
    - hostvars[item] is defined
    - hostvars[item].network is defined
    - hostvars[item].network == 'ephemery'
  register: host_vars_updated
  failed_when: false

- name: Ensure sync_strategy is set to genesis
  ansible.builtin.lineinfile:
    path: "{{ inventory_dir }}/host_vars/{{ item }}.yaml"
    regexp: "sync_strategy:.*"
    line: "sync_strategy: \"genesis\""
    state: present
    backup: yes
  become: false
  delegate_to: localhost
  with_items: "{{ groups['all'] | default([]) }}"
  when:
    - hostvars[item] is defined
    - hostvars[item].network is defined
    - hostvars[item].network == 'ephemery'
  register: sync_strategy_updated
  failed_when: false

- name: Add optimized genesis sync parameters
  ansible.builtin.lineinfile:
    path: "{{ inventory_dir }}/host_vars/{{ item }}.yaml"
    regexp: "cl_extra_opts:.*"
    line: "cl_extra_opts: \"--target-peers=100 --execution-timeout-multiplier=5 --allow-insecure-genesis-sync --genesis-backfill --disable-backfill-rate-limiting\""
    state: present
    backup: yes
  become: false
  delegate_to: localhost
  with_items: "{{ groups['all'] | default([]) }}"
  when:
    - hostvars[item] is defined
    - hostvars[item].network is defined
    - hostvars[item].network == 'ephemery'
    - hostvars[item].cl is defined
    - hostvars[item].cl == 'lighthouse'
  register: cl_params_updated
  failed_when: false

- name: Add optimized execution client parameters
  ansible.builtin.lineinfile:
    path: "{{ inventory_dir }}/host_vars/{{ item }}.yaml"
    regexp: "el_extra_opts:.*"
    line: "el_extra_opts: \"--cache=4096 --txlookuplimit=0 --syncmode=snap --maxpeers=100\""
    state: present
    backup: yes
  become: false
  delegate_to: localhost
  with_items: "{{ groups['all'] | default([]) }}"
  when:
    - hostvars[item] is defined
    - hostvars[item].network is defined
    - hostvars[item].network == 'ephemery'
    - hostvars[item].el is defined
    - hostvars[item].el == 'geth'
  register: el_params_updated
  failed_when: false

- name: Create a playbook to apply genesis sync
  ansible.builtin.copy:
    content: |
      ---
      # Playbook to switch all Ephemery nodes to genesis sync
      - name: Switch Ephemery Nodes to Genesis Sync
        hosts: ephemery
        become: true
        gather_facts: true
        vars:
          network: "{{ network | default('ephemery') }}"

        tasks:
          - name: Stop Consensus Client container
            community.docker.docker_container:
              name: "{{ network }}-{{ cl }}"
              state: stopped
            when: cl is defined
            ignore_errors: true

          - name: Clear consensus client database for clean genesis sync
            ansible.builtin.file:
              path: "{{ ephemery_dir }}/data/{{ cl }}"
              state: absent
            when: cl is defined

          - name: Create consensus client data directory
            ansible.builtin.file:
              path: "{{ ephemery_dir }}/data/{{ cl }}"
              state: directory
              mode: "0755"
            when: cl is defined

          - name: Start consensus client with genesis sync
            community.docker.docker_container:
              name: "{{ network }}-{{ cl }}"
              image: "{{ client_images[cl] }}"
              state: started
              restart_policy: unless-stopped
              network_mode: host
              volumes:
                - "{{ ephemery_dir }}/data/{{ cl }}:/data"
                - "{{ ephemery_dir }}/jwt.hex:/jwt.hex"
                - "{{ ephemery_dir }}/config/ephemery_network:/ephemery_config:ro"
              command: >
                {% if cl == "lighthouse" %}
                lighthouse beacon_node
                --datadir=/data
                --execution-jwt=/jwt.hex
                --execution-endpoint=http://127.0.0.1:8551
                --http
                --http-address=0.0.0.0
                --http-port=5052
                --metrics
                --metrics-address=0.0.0.0
                --metrics-port=5054
                --testnet-dir=/ephemery_config
                --target-peers=100
                --execution-timeout-multiplier=5
                --allow-insecure-genesis-sync
                --genesis-backfill
                --disable-backfill-rate-limiting
                {{ cl_extra_opts | default('') }}
                {% endif %}
            when: cl is defined and cl == "lighthouse"

          - name: Check consensus client sync status
            ansible.builtin.uri:
              url: "http://localhost:{{ cl_client_port }}/eth/v1/node/syncing"
              method: GET
              return_content: true
            register: cl_sync_status
            failed_when: false
            when: cl is defined

          - name: Display consensus client sync status
            ansible.builtin.debug:
              msg: "{{ cl_sync_status.json.data }}"
            when: cl is defined and cl_sync_status.status is defined and cl_sync_status.status == 200
    dest: "{{ playbook_dir }}/../playbooks/switch_to_genesis_sync.yaml"
    mode: "0644"
  become: false
  delegate_to: localhost

- name: Display results summary
  ansible.builtin.debug:
    msg: |
      Successfully updated configuration for genesis sync:
      - Host vars updated: {{ host_vars_updated.changed | default(false) }}
      - Sync strategy updated: {{ sync_strategy_updated.changed | default(false) }}
      - Consensus client parameters updated: {{ cl_params_updated.changed | default(false) }}
      - Execution client parameters updated: {{ el_params_updated.changed | default(false) }}

      To apply these changes to your nodes, run:
      ansible-playbook -i your_inventory playbooks/switch_to_genesis_sync.yaml
