---
# Prysm-specific configuration tasks

- name: Set Prysm-specific variables
  ansible.builtin.set_fact:
    prysm_data_dir: "{{ ephemery_data_dir }}/{{ cl_client_name }}"
    prysm_http_port: "{{ cl_client_port }}"
    prysm_p2p_port: "{{ cl_p2p_port }}"
    prysm_metrics_port: '{{ cl_metrics_port | default("8080") }}'

- name: Create Prysm data directory
  ansible.builtin.file:
    path: "{{ prysm_data_dir }}"
    state: directory
    mode: "0755"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Ensure metrics port is different from HTTP API port
  ansible.builtin.set_fact:
    prysm_metrics_port: 8080
  when: prysm_metrics_port == prysm_http_port
