---
# Hard-coded variables for Ephemery
# These values are not meant to be overridden by default variables
# They are primarily used for internal configuration and references

# Repository information
repository_url: https://github.com/ephemery-testnet/ephemery-scripts.git
branch: master

# Default Docker image references
client_images:
  # Execution clients
  # Note: For Ephemery network, consider using pk910/ephemery-geth instead
  geth: ethereum/client-go:v1.15.4
  besu: hyperledger/besu:24.7.2
  nethermind: nethermind/nethermind:1.27.1
  reth: paradigmxyz/reth:v0.2.0
  erigon: thorax/erigon:v2.59.0

  # Consensus clients
  # Note: For Ephemery network, consider using pk910/ephemery-lighthouse instead
  lighthouse: sigp/lighthouse:v5.3.0
  teku: consensys/teku:24.10.0
  prysm: prysmaticlabs/prysm-beacon-chain:v5.0.1
  lodestar: chainsafe/lodestar:v1.16.0

  # Other
  validator: sigp/lighthouse:v5.3.0 # Default validator image
  watchdog: jer117/watchdog-container:v0.0.3-story-geth

# File paths for reference
files:
  validator_keys: files/validator-keys/
  default_configs:
    geth: files/geth-conf.example
    besu: files/besu-conf.example
    nethermind: files/nethermind-conf.example
    reth: files/reth-conf.example
    lighthouse: files/lighthouse-conf.example
    teku: files/teku-conf.example
    prysm: files/prysm-conf.example

# Docker volume mounting config
host_el_data_mount: "{{ el }}-data"
host_cl_data_mount: "{{ cl }}-data"
host_keys_mount: "{{ files.validator_keys }}"

#
#
# ##############################################################################################
# ##############################################################################################
# CHOOSE YOUR FIGHTERS: for the ephemery testnet -- resetter built-in
# Cadvisor Vars
# Grafana Agent Vars
# Node Exporter Vars
# Repository Vars
# Set docker container memory limit to 90% of available machine memory
# Watchdog Vars
# geth_image: 'pk910/ephemery-geth:latest'
# host / docker mounts
# lighthouse_image: 'pk910/ephemery-lighthouse:latest'
# nimbus_image: 'pk910/ephemery-nimbus:latest'
# prometheus ports
# reth_image: 'pk910/ephemery-reth:latest'
# validator client specific config and keys

# Default variable values for the Ephemery role

# Docker compose version to install
docker_compose_version: 2.25.0

# Home directory for the deployment
home_dir: /opt/ephemery

# Docker network configuration
docker_network_name: ephemery
docker_network_subnet: 172.20.0.0/24

# JWT secret file path
jwt_secret_path: "{{ home_dir }}/jwt/jwtsecret"
jwt_secret_secure_generation: true # Use more secure random generation

# Client configurations
consensus_client: lighthouse # Options: lighthouse, teku, prysm, nimbus, lodestar
execution_client: geth # Options: geth, nethermind, besu, erigon, reth

# Hardware resource limits
execution_memory_limit: 8g
consensus_memory_limit: 8g
validator_memory_limit: 2g

# Services to enable
validator_enabled: false
monitoring_enabled: true
backup_enabled: false
firewall_enabled: false
cadvisor_enabled: true

# Network ports (external/host)
http_port: 8545
ws_port: 8546
engine_port: 8551
consensus_port: 5052
p2p_port: 30303 # p2p port for execution client
p2p_udp_port: 30303 # p2p udp port for execution client
cl_p2p_port: 9000 # p2p port for consensus client
cl_p2p_udp_port: 9000 # p2p udp port for consensus client
monitoring_port: 3000 # Grafana
