---
- name: Converge
  hosts: all
  tasks:
    - name: Include ansible-ephemery role
      include_role:
        name: ../../
      vars:
        # Override variables for testing
        home_dir: /root
