---
# Default scenario configuration that imports the base configuration
# Extends the shared base configuration

dependency:
  name: galaxy
driver:
  name: docker
  options:
    docker_host: unix:///Users/droo/.docker/run/docker.sock
    # Alternate options if the above doesn't work:
    # docker_host: tcp://localhost:2375
    # docker_host: unix:///Users/droo/Library/Containers/com.docker.docker/Data/docker-cli.sock
platforms:
  - name: ethereum-node
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      # Docker socket mount removed to fix issues on macOS
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    host_vars:
      ethereum-node:
        # Import values from shared host_vars and override as needed
        el: geth
        cl: lighthouse
        # Other variables are inherited from shared/host_vars/ethereum-node/main.yaml
verifier:
  name: ansible
