---
# Default scenario configuration that imports the base configuration
# Extends the shared base configuration

dependency:
  name: galaxy
driver:
  name: docker
  options:
    docker_host: unix:///Users/droo/Library/Containers/com.docker.docker/Data/docker-cli.sock
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu:latest
    pre_build_image: true
provisioner:
  name: ansible
verifier:
  name: ansible
