---
# Default scenario configuration that imports the base configuration
# Extends the shared base configuration

dependency:
  name: galaxy
driver:
  name: docker
  options:
    # Docker socket connection options - the script will replace this
    docker_host: ${DOCKER_HOST:-unix:///var/run/docker.sock}
platforms:
  - name: ethereum-node
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
provisioner:
  name: ansible
  inventory:
    host_vars:
      ethereum-node:
        # Import values from shared host_vars and override as needed
        el: geth
        cl: lighthouse
        # Other variables are inherited from shared/host_vars/ethereum-node/main.yaml
verifier:
  name: ansible
