---
# Default scenario configuration that imports the base configuration
# Extends the shared base configuration

dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: ethereum-node
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      - /var/run/docker.sock:/var/run/docker.sock
    command: "/lib/systemd/systemd"
provisioner:
  name: ansible
  inventory:
    host_vars:
      ethereum-node:
        # Import values from shared host_vars and override as needed
        el: geth
        cl: lighthouse
        # Other variables are inherited from shared/host_vars/ethereum-node/main.yaml
verifier:
  name: ansible
