---
- name: Prepare
  hosts: all
  tasks:
    - name: Create home directory for testing
      file:
        path: /root/ephemery
        state: directory
        mode: '0755'

    # Skip package installs to avoid network dependency issues during testing

    - name: Ensure Docker directory exists
      file:
        path: /var/lib/docker
        state: directory
        mode: '0755'

    - name: Create mock Docker files
      file:
        path: "{{ item }}"
        state: touch
        mode: '0644'
      with_items:
        - /root/ephemery/docker-compose.yml
