---
- name: Prepare
  hosts: all
  tasks:
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
          - python3-pip
          - docker.io
          - jq
        state: present
        update_cache: true

    - name: Ensure Docker service is running
      service:
        name: docker
        state: started
        enabled: true

    - name: Create Docker network for testing
      docker_network:
        name: ephemery-validator-net
        state: present
