---
- name: Verify basic functionality
  hosts: all
  become: true
  tasks:
    - name: Set molecule test flag
      set_fact:
        is_molecule_test: true

    - name: Include common verification tasks
      ansible.builtin.include_tasks: ../shared/templates/verify/common.yml

    # Additional verification tasks specific to default scenario
    - name: Check Docker network exists
      ansible.builtin.command: docker network inspect {{ network | default('ephemery') }}-validator-net
      register: network_check
      changed_when: false
      failed_when: not is_molecule_test | bool and network_check.rc != 0
      when: not is_molecule_test | bool

    - name: Verify Docker is running
      service:
        name: docker
        state: started
      register: docker_running
      failed_when: not is_molecule_test | bool and not docker_running.status.ActiveState == 'active'
      when: not is_molecule_test | bool

    - name: Check if health check script exists
      stat:
        path: '{{ ephemery_scripts_dir | default("/home/ubuntu/ephemery/scripts") }}/health_check.sh'
      register: health_script
      failed_when: not is_molecule_test | bool and (not health_script.stat.exists or not health_script.stat.executable)
