---
# Main playbook for Ephemery node deployment

- name: Include required collections
  hosts: localhost
  gather_facts: false
  tasks:
    - name: Display collections
      ansible.builtin.debug:
        msg: 'Required collections have been included'

- name: Update Ephemery Nodes
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - ../defaults/main.yaml
    - ../vars/main.yaml
  tasks:
    - name: Load host-specific variables
      ansible.builtin.include_vars:
        file: '../host_vars/{{ inventory_hostname }}.yaml'

    - name: Pull latest execution client Docker image
      community.docker.docker_image:
        name: '{{ client_images[el] }}'
        source: pull
        force_source: false
      when: el is defined

    - name: Pull latest consensus client Docker image
      community.docker.docker_image:
        name: '{{ client_images[cl] }}'
        source: pull
        force_source: false
      when: cl is defined

    - name: Pull latest validator client Docker image (if enabled)
      community.docker.docker_image:
        name: '{{ client_images.validator }}'
        source: pull
        force_source: false
      when: validator_enabled | default(false) | bool

- name: 🏖️ Deploy Ephemery Nodes
  hosts: ephemery
  become: true
  vars:
    # Use the directories structure from inventory if available, otherwise fall back to defaults
    ephemery_base_dir: "{{ directories.base | default('/root/ephemery') }}"
    ephemery_data_dir: "{{ directories.data | default('/root/ephemery/data') }}"
    ephemery_secrets_dir: "{{ directories.secrets | default('/root/ephemery/secrets') }}"
    ephemery_logs_dir: "{{ directories.logs | default('/root/ephemery/logs') }}"
    ephemery_scripts_dir: "{{ directories.scripts | default('/root/ephemery/scripts') }}"
    ephemery_backup_dir: "{{ directories.backups | default('/root/ephemery/backups') }}"
    # For backward compatibility with tasks that use ephemery_dir
    ephemery_dir: "{{ directories.base | default('/root/ephemery') }}"
    # Set JWT secret path from inventory or default
    jwt_secret_path: "{{ jwt_secret_path | default('/root/ephemery/jwt.hex') }}"
  tasks:
    - name: 🏖️ Create cozy axolotl home directory 🏖️
      ansible.builtin.file:
        path: "{{ ephemery_base_dir }}"
        state: directory
        mode: "0755"
        owner: "{{ ansible_user | default('root') }}"
        group: "{{ ansible_user | default('root') }}"

    - name: Import main tasks
      ansible.builtin.import_tasks: ../tasks/main.yaml

- name: Configure Periodic Reset for Ephemery Nodes
  hosts: all
  become: true
  gather_facts: true
  vars_files:
    - ../defaults/main.yaml
    - ../vars/main.yaml
  tasks:
    - name: Load host-specific variables
      ansible.builtin.include_vars:
        file: '../host_vars/{{ inventory_hostname }}.yaml'

    - name: Setup periodic reset tasks
      ansible.builtin.import_tasks: ../tasks/periodic_reset.yaml
      when: ephemery_automatic_reset | default(false) | bool
