---
# Optimized Ephemery Sync Playbook

- name: Ephemery Fast Sync Setup
  hosts: ephemery
  become: true
  gather_facts: true
  vars:
    ephemery_base_dir: "/opt/ephemery"
    ephemery_dir: "{{ ephemery_base_dir }}"
    ephemery_scripts_dir: "{{ ephemery_base_dir }}/scripts"
    ephemery_data_dir: "{{ ephemery_base_dir }}/data"
    ephemery_logs_dir: "{{ ephemery_base_dir }}/logs"
    jwt_secret_path: "{{ ephemery_dir }}/jwt.hex"
  vars_files:
    - ../defaults/main.yaml
    - ../vars/main.yaml
  tasks:
    - name: Import custom fast sync tasks
      ansible.builtin.import_tasks: ../tasks/fast-sync-tasks.yaml

    # First, ensure the environment is set up correctly
    - name: Create directory structure
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "{{ ephemery_base_dir }}"
        - "{{ ephemery_data_dir }}"
        - "{{ ephemery_scripts_dir }}"
        - "{{ ephemery_logs_dir }}"

    # Import main Ephemery tasks
    - name: Import main Ephemery tasks
      ansible.builtin.import_tasks: ../tasks/main.yaml

    # Add post-deployment monitoring
    - name: Check sync status after deployment
      ansible.builtin.shell: "{{ ephemery_scripts_dir }}/check_sync_status.sh"
      register: sync_status
      failed_when: false
      changed_when: false

    - name: Display sync status
      ansible.builtin.debug:
        var: sync_status.stdout_lines
