---
# Main Ephemery Deployment Playbook

- name: Deploy Ephemery Testnet Nodes
  hosts: ephemery
  become: true

  # Pre-tasks: Load all variables and verify requirements are met
  pre_tasks:
    - name: Import centralized variable management
      ansible.builtin.include_tasks: ../vars_management.yaml

    - name: Verify deployment environment
      ansible.builtin.fail:
        msg: "Insufficient memory for Ephemery deployment. Minimum 4GB required."
      when: ansible_memory_mb.real.total < 4096

  # Tasks for deploying Ephemery nodes
  tasks:
    # Setup base directories
    - name: Create Ephemery directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ directories.base }}"
        - "{{ directories.data }}"
        - "{{ directories.secrets }}"
        - "{{ directories.logs }}"
        - "{{ directories.scripts }}"
        - "{{ directories.backups }}"
        - "{{ lighthouse.config_dir }}"
        - "{{ geth.config_dir }}"
        - "{{ validator.config_dir }}"

    # Setup security components
    - name: Generate JWT secret
      ansible.builtin.include_tasks: ../tasks/jwt-secret.yaml

    # Deploy Docker containers
    - name: Deploy Execution Client (Geth)
      ansible.builtin.include_tasks: clients/execution_client.yaml
      vars:
        client_type: "{{ clients.execution }}"

    - name: Deploy Consensus Client (Lighthouse)
      ansible.builtin.include_tasks: clients/consensus_client.yaml
      vars:
        client_type: "{{ clients.consensus }}"

    - name: Deploy Validator Client (if enabled)
      ansible.builtin.include_tasks: validator.yaml
      when: features.validator.enabled | bool

    # Final verification
    - name: Display Ephemery node information
      ansible.builtin.debug:
        msg: |
          Ephemery node is now running
          --------------------------
          Execution client: {{ clients.execution | upper }}
          Consensus client: {{ clients.consensus | upper }}
          Validator enabled: {{ features.validator.enabled | bool }}
          Monitoring enabled: {{ features.monitoring.enabled | bool }}
          --------------------------
          Management dashboard: http://{{ ansible_host }}:{{ ports.monitoring.grafana }}
          (if monitoring is enabled)

  handlers:
    - name: Reload cadvisor
      ansible.builtin.systemd:
        name: cadvisor.service
        state: restarted

    - name: Extract Ephemery network configuration
      ansible.builtin.unarchive:
        src: '{{ ephemery_dir }}/config/ephemery_network/testnet-all.tar.gz'
        dest: '{{ ephemery_dir }}/config/ephemery_network'
        remote_src: true
        mode: '0755'
        owner: '{{ ansible_user | default("root") }}'
        group: '{{ ansible_user | default("root") }}'

# Import additional playbooks
- name: Import firewall setup playbook
  ansible.builtin.import_playbook: firewall_setup.yaml
  when: security.firewall_enabled | bool

- name: Import monitoring playbook
  ansible.builtin.import_playbook: monitoring.yaml
  when: features.monitoring.enabled | bool

- name: Import backup playbook
  ansible.builtin.import_playbook: backup.yaml
  when: features.backup.enabled | bool

- name: Import sync status check playbook
  ansible.builtin.import_playbook: check_sync_status.yaml
