---
- name: Create directory structure for cadvisor
  ansible.builtin.file:
    path: '{{ home_dir }}/cadvisor'
    state: directory
    owner: '{{ ansible_user | default("root") }}'
    mode: '0755'
  when: not test_mode | default(false)

- name: Install cadvisor
  community.docker.docker_container:
    name: cadvisor
    image: gcr.io/cadvisor/cadvisor:v0.47.0
    state: >-
      {{ 'started' if cadvisor_enabled | default(true) | bool else 'absent' }}
    restart_policy: unless-stopped
    network_mode: host
    privileged: true
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    command:
      - --port={{ cadvisor_port }}
      - --enable_metrics=process,memory,network,oom_event,disk
    security_opts:
      - label=disable
  become: true
  become_user: '{{ ansible_user | default("root") }}'
  when: not test_mode | default(false)
