---
- name: Ensure ephemery directory exists
  ansible.builtin.file:
    path: '{{ ephemery_base_dir }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Check if secure JWT generation is enabled
  ansible.builtin.set_fact:
    use_vault: false

# Standard JWT secret generation (less secure)
- name: Generate JWT secret with openssl
  ansible.builtin.shell: |
    # Ensure parent directory exists
    mkdir -p $(dirname {{ jwt_secret_path }})
    # Remove any existing directory with the same name as the JWT file
    if [ -d '{{ jwt_secret_path }}' ]; then
      rm -rf '{{ jwt_secret_path }}'
    fi
    # Generate the JWT secret file
    echo -n 0x$(openssl rand -hex 32 | tr -d "\n") > {{ jwt_secret_path }}
    chmod 600 {{ jwt_secret_path }}
  args:
    creates: '{{ jwt_secret_path }}'
  register: jwt_secret_result
  changed_when: jwt_secret_result.rc == 0

- name: Ensure JWT secret has proper permissions
  ansible.builtin.file:
    path: '{{ jwt_secret_path }}'
    mode: '0600'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
