---
  # Main tasks file for Ephemery Ansible

- name: Include setup environment tasks
  ansible.builtin.include_tasks:
    file: setup-env.yaml
  tags:
    - always

- name: Include security setup tasks
  ansible.builtin.include_tasks:
    file: security.yaml
  tags:
    - security

- name: Include JWT Secret Generation tasks
  ansible.builtin.include_tasks:
    file: jwt-secret.yaml
  tags:
    - jwt
    - startup

- name: Setup Ephemery Network Configuration
  ansible.builtin.include_tasks:
    file: ephemery_config.yaml
  tags:
    - config
    - startup

- name: Execute Client specific tasks
  ansible.builtin.include_tasks:
    file: ephemery.yaml
  tags:
    - startup

- name: Setup Validator
  ansible.builtin.include_tasks:
    file: validator.yaml
  tags:
    - validator

- name: Set up synchronization status monitoring
  ansible.builtin.include_tasks:
    file: sync-status-monitor.yaml
  tags:
    - monitoring
    - sync
  when: sync_monitoring_enabled | default(true) | bool

- name: Setup monitoring tools
  ansible.builtin.include_tasks:
    file: monitoring.yaml
  tags:
    - monitoring
  when: monitoring_enabled | default(true) | bool

- name: Setup periodic reset tasks
  ansible.builtin.include_tasks:
    file: periodic_reset.yaml
  tags:
    - maintenance
  when: reset_enabled | default(false) | bool

- name: Setup backup tasks
  ansible.builtin.include_tasks:
    file: backup.yaml
  tags:
    - backup
  when: backup_enabled | default(false) | bool
