---
  # Main tasks file for ansible-ephemery role


- name: Include setup environment tasks
  ansible.builtin.import_tasks: setup-env.yaml
  tags: [setup, always]

- name: Configure security (JWT and firewall)
  ansible.builtin.import_tasks: security.yaml
  tags: [security, jwt, firewall, always]

- name: Include ephemery tasks
  ansible.builtin.import_tasks: ephemery.yaml
  tags: [ephemery, always]

- name: Setup validator if enabled
  ansible.builtin.import_tasks: validator.yaml
  when: validator_enabled | default(true) | bool
  tags: [validator]

- name: Include monitoring tasks
  ansible.builtin.import_tasks: monitoring.yaml
  when: monitoring_enabled | default(true) | bool
  tags: [monitoring, always]

- name: Install Cadvisor
  ansible.builtin.import_tasks: cadvisor.yaml
  when: cadvisor_enabled | default(true) | bool
  tags: [cadvisor, monitoring]

- name: Setup automatic backups
  ansible.builtin.import_tasks: backup.yaml
  when: backup_enabled | default(true) | bool
  tags: [backup]
