---
  # Tasks for setting up periodic resets of Ephemery nodes


- name: Create script directory if it doesn't exist
  ansible.builtin.file:
    path: '{{ ephemery_scripts_dir }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Copy reset script
  ansible.builtin.template:
    src: templates/scripts/reset_ephemery.sh.j2
    dest: '{{ ephemery_scripts_dir }}/reset_ephemery.sh'
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Create log directory if it doesn't exist
  ansible.builtin.file:
    path: '{{ ephemery_logs_dir }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'

- name: Parse ephemery_reset_frequency into cron components
  ansible.builtin.set_fact:
    cron_minute: "{{ ephemery_reset_frequency.split(' ')[0] }}"
    cron_hour: "{{ ephemery_reset_frequency.split(' ')[1] }}"
    cron_day: "{{ ephemery_reset_frequency.split(' ')[2] }}"
    cron_month: "{{ ephemery_reset_frequency.split(' ')[3] }}"
    cron_weekday: "{{ ephemery_reset_frequency.split(' ')[4] }}"
  when: ephemery_automatic_reset | default(false) | bool

- name: Set up cron job for periodic resets
  ansible.builtin.cron:
    name: "Reset Ephemery nodes"
    minute: "{{ cron_minute }}"
    hour: "{{ cron_hour }}"
    day: "{{ cron_day }}"
    month: "{{ cron_month }}"
    weekday: "{{ cron_weekday }}"
    job: "{{ ephemery_scripts_dir }}/reset_ephemery.sh > {{ ephemery_logs_dir }}/reset.log 2>&1"
    user: "{{ ansible_user }}"
  when: ephemery_automatic_reset | default(false) | bool
