---
# Synchronization Status Monitoring
# Implementation of the Ephemery Improvement Plan v1.0.0

- name: Ensure monitoring prerequisites
  ansible.builtin.package:
    name:
      - python3
      - jq
      - nginx
    state: present
  when: sync_dashboard_enabled | default(false) | bool

- name: Create synchronization monitoring directories
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - "{{ ephemery_base_dir }}/data/monitoring/sync"
    - "{{ ephemery_base_dir }}/data/monitoring/sync/dashboard"
    - "{{ ephemery_base_dir }}/data/monitoring/sync/dashboard/data"
    - "{{ ephemery_base_dir }}/scripts"

- name: Create sync monitoring script
  ansible.builtin.template:
    src: sync_monitor.sh.j2
    dest: "{{ ephemery_base_dir }}/scripts/sync_monitor.sh"
    mode: '0755'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"

- name: Setup sync monitoring cron job
  ansible.builtin.cron:
    name: "Monitor sync status"
    minute: "*/{{ (sync_monitor_interval | default(300) / 60) | int }}"
    job: "{{ ephemery_base_dir }}/scripts/sync_monitor.sh > {{ ephemery_base_dir }}/data/monitoring/sync/monitor.log 2>&1"
    user: "{{ ansible_user }}"

- name: Run initial sync monitoring
  ansible.builtin.shell: |
    {{ ephemery_base_dir }}/scripts/sync_monitor.sh
  args:
    executable: /bin/bash
  register: initial_sync_monitor
  changed_when: false

- name: Display sync status information
  ansible.builtin.debug:
    msg: "{{ initial_sync_monitor.stdout_lines }}"
  when: initial_sync_monitor is defined and initial_sync_monitor.stdout_lines is defined

# Web Dashboard Setup
- name: Deploy dashboard files
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    mode: '0644'
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
  loop:
    - { src: 'sync_dashboard.html.j2', dest: '{{ ephemery_base_dir }}/data/monitoring/sync/dashboard/index.html' }
    - { src: 'sync-report-generator.py.j2', dest: '{{ ephemery_base_dir }}/scripts/sync-report-generator.py', mode: '0755' }
  when: sync_dashboard_enabled | default(false) | bool

- name: Create symbolic links to data files
  ansible.builtin.file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  loop:
    - { src: '{{ ephemery_base_dir }}/data/monitoring/sync/current_status.json', dest: '{{ ephemery_base_dir }}/data/monitoring/sync/dashboard/data/current_status.json' }
    - { src: '{{ ephemery_base_dir }}/data/monitoring/sync/history.json', dest: '{{ ephemery_base_dir }}/data/monitoring/sync/dashboard/data/history.json' }
  when: sync_dashboard_enabled | default(false) | bool

- name: Configure nginx for dashboard
  become: yes
  ansible.builtin.template:
    src: nginx-dashboard.conf.j2
    dest: /etc/nginx/conf.d/ephemery-dashboard.conf
    mode: '0644'
  notify: restart nginx
  when: sync_dashboard_enabled | default(false) | bool

- name: Create nginx handler
  ansible.builtin.meta: flush_handlers
  when: sync_dashboard_enabled | default(false) | bool

- name: Ensure nginx is running
  become: yes
  ansible.builtin.service:
    name: nginx
    state: started
    enabled: yes
  when: sync_dashboard_enabled | default(false) | bool

- name: Display dashboard access information
  ansible.builtin.debug:
    msg: |
      Sync dashboard is now available at:
      http://{{ ansible_default_ipv4.address | default('YOUR_SERVER_IP') }}/ephemery-status/
  when: sync_dashboard_enabled | default(false) | bool
