---
# Firewall rules for Reth (execution client) and Lodestar
# (consensus client) combination
- name: Set firewall ports for reth-lodestar
  ansible.builtin.set_fact:
    firewall_allowed_tcp_ports:
      - 22 # SSH
      - 80 # HTTP
      - 443 # HTTPS
      - 30303 # Reth P2P
      - 8551 # Reth Engine API
      - 9000 # Lodestar P2P
      - 8008 # Lodestar API
    firewall_allowed_udp_ports:
      - 30303 # Reth P2P
      - 9000 # Lodestar P2P
