---
# This is a molecule configuration file, not an Ansible playbook
# noqa: playbook-syntax
# Base molecule configuration to be imported by other scenarios
dependency:
  name: galaxy
driver:
  name: docker
  # Docker host configuration will be set by update-molecule-configs.sh script
  # to match the environment-specific Docker socket path
platforms: &base_platforms
  - name: &platform_name ethereum-node
    image: ubuntu:22.04
    pre_build_image: true
    privileged: true
    volumes:
      # Cgroup mount options updated by script:
      # - ro for Linux
      # - rw for macOS
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
      # Docker socket path updated by script based on environment
      - /var/run/docker.sock:/var/run/docker.sock
    command: "/lib/systemd/systemd"
    # cgroupns_mode: host will be added for macOS by the script
provisioner: &base_provisioner
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
  inventory:
    links:
      group_vars: ../../molecule/shared/group_vars/
      host_vars: ../../molecule/shared/host_vars/
verifier: &base_verifier
  name: ansible
