---
# This is a molecule configuration file, not an Ansible playbook
# noqa: playbook-syntax
# yaml-language-server: $schema=https://raw.githubusercontent.com/ansible/ansible-lint/main/src/ansiblelint/schemas/molecule.json
# ansible-lint: ignore=playbook-syntax
# ansible-lint: ignore=syntax-check
# ansible-lint: ignore=yaml
# Base molecule configuration to be imported by other scenarios on macOS
dependency:
  name: galaxy
driver:
  name: docker
platforms: &base_platforms
  - name: &platform_name ethereum-node
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    pre_build_image: true
    privileged: true
    volumes:
      # Cgroup mount options for macOS
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
      # Docker socket path will be set from the environment variable
      - "{{ '{{' }} lookup('env', 'DOCKER_SOCKET_PATH') | default('/var/run/docker.sock') {{ '}}' }}:/var/run/docker.sock"
    command: '/lib/systemd/systemd'
    cgroupns_mode: host
provisioner: &base_provisioner
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: true
    DOCKER_HOST: "{{ '{{' }} lookup('env', 'DOCKER_HOST') {{ '}}' }}"
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer
  inventory:
    links:
      group_vars: ../../molecule/shared/group_vars/
      host_vars: ../../molecule/shared/host_vars/
verifier: &base_verifier
  name: ansible
