---
# Common preparation tasks for molecule scenarios
# Usage: - import_playbook: ../../shared/prepare.yml

- name: Prepare
  hosts: all
  become: true
  vars:
    ephemery_base_dir: "{{ ephemery_base_dir | default('/home/ubuntu/ephemery') }}"
  tasks:
    - name: Update apt cache
      apt:
        update_cache: true
        cache_valid_time: 3600

    - name: Install common dependencies
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
          - python3-pip
          - software-properties-common
        state: present

    - name: Create Ephemery directories
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ephemery_base_dir }}"
        - "{{ ephemery_base_dir }}/data"
        - "{{ ephemery_base_dir }}/logs"
        - "{{ ephemery_base_dir }}/scripts"
        - "{{ ephemery_base_dir }}/backups"
