---
- name: Check if client combination is selected
  ansible.builtin.set_fact:
    client_skip: '{{ not (el == "nethermind" and cl == "prysm") }}'

- name: 🌟 Ensure client directories exist
  ansible.builtin.file:
    path: '{{ item }}'
    state: directory
    mode: '0755'
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
  loop:
    - '{{ ephemery_data_dir }}/el'
    - '{{ ephemery_data_dir }}/cl'
    - '{{ ephemery_logs_dir }}'
  when: not client_skip

- name: 🔑 Ensure JWT secret exists
  ansible.builtin.import_tasks:
    file: tasks/jwt-secret.yaml
  when: not client_skip

- name: 🚀 Start Nethermind (Execution Client)
  community.docker.docker_container:
    name: '{{ network }}-nethermind'
    image: 'pk910/ephemery-nethermind:v1.25.2'
    state: started
    pull: true
    restart_policy: unless-stopped
    network_mode: host
    memory: '{{ el_memory_limit }}'
    volumes:
      - '{{ jwt_secret_path }}:/execution-auth.jwt:ro'
      - '{{ ephemery_data_dir }}/el:/data'
    command: >
      --datadir=/data
      --Network.DiscoveryPort=30303
      --Network.P2PPort=30303
      --JsonRpc.Enabled=true
      --JsonRpc.Host=0.0.0.0
      --JsonRpc.Port=8545
      --JsonRpc.JwtSecretFile=/execution-auth.jwt
      --JsonRpc.EnabledModules=[Web3,Eth,Subscribe,Net,Trace]
      --Metrics.Enabled=true
      --Metrics.ExposePort=9091
  when: not client_skip

- name: 🚀 Start Prysm (Consensus Client)
  community.docker.docker_container:
    name: '{{ network }}-prysm'
    image: 'pk910/ephemery-prysm:v4.1.1'
    state: started
    pull: true
    restart_policy: unless-stopped
    network_mode: host
    memory: '{{ cl_memory_limit }}'
    volumes:
      - '{{ jwt_secret_path }}:/execution-auth.jwt:ro'
      - '{{ ephemery_data_dir }}/cl:/data'
    command: >
      --datadir=/data
      --ephemery-network
      --accept-terms-of-use
      --rpc-host=0.0.0.0
      --rpc-port=3500
      --grpc-gateway-host=0.0.0.0
      --grpc-gateway-port=3501
      --monitoring-host=0.0.0.0
      --monitoring-port=9999
      --p2p-tcp-port=9001
      --p2p-udp-port=9001
      --execution-endpoint=http://127.0.0.1:8551
      --jwt-secret=/execution-auth.jwt
      --disable-blst
  when: not client_skip
