---
# Firewall rules for Reth (execution client) and Lighthouse (consensus client) combination
firewall_allowed_tcp_ports:
  - 22    # SSH
  - 80    # HTTP
  - 443   # HTTPS
  - 30303 # Reth P2P
  - 8551  # Reth Engine API
  - 9000  # Lighthouse P2P
  - 5052  # Lighthouse metrics

firewall_allowed_udp_ports:
  - 30303 # Reth P2P
  - 9000  # Lighthouse P2P
