---
# Ephemery Network-Specific Configuration

# Network identity
network:
  name: "ephemery"
  description: "Ephemery Testnet (24-hour reset cycle)"
  chain_id: 39337

# Ephemery-specific settings
ephemery:
  # Network reset configuration
  reset:
    frequency: "0 0 * * *" # Midnight every day (cron format)
    preload_genesis: true # Preload genesis for faster restart
    backup_before_reset: true # Create backup before network reset

  # Ephemery-specific endpoints
  endpoints:
    explorer: "https://explorer.ephemery.dev/"
    faucet: "https://faucet.ephemery.dev/"

  # Bootstrap nodes specific to Ephemery network
  bootstrap_nodes:
    - "/ip4/157.90.35.151/tcp/9000/udp/9000/p2p/16Uiu2HAmVZnsqvTNQ2ya1YG2qi6DQchqX57jF9zN2CukZnQY84wJ"
    - "/ip4/136.243.15.66/tcp/9000/udp/9000/p2p/16Uiu2HAmAwGWqGShumBQeUuivDyRMmCZjvbZsQwcEWYYLDVKvFjG"
    - "/ip4/88.198.2.150/tcp/9000/udp/9000/p2p/16Uiu2HAm8cEfaKtweXbT4koAuifKKJPm8q7TdpaVfWk9j5E5L2m3"
    - "/ip4/135.181.91.151/tcp/9000/udp/9000/p2p/16Uiu2HAmEP7X3JDcdAYLagNQxpJ24n3HDwLGxVVsWyv2aUHrXA5b"

# Client images for Ephemery
client_images:
  geth: "pk910/ephemery-geth:latest"
  lighthouse: "pk910/ephemery-lighthouse:latest"
  validator: "pk910/ephemery-lighthouse:latest"

# Network-specific client settings
client_settings:
  geth:
    options:
      # Ephemery-optimized settings
      txlookuplimit: 0
      syncmode: "snap"

  lighthouse:
    options:
      # Ephemery-optimized settings
      allow_insecure_genesis_sync: true
      genesis_backfill: true
      disable_backfill_rate_limiting: true
