---
molecule:
  scenario:
    create_sequence:
      - dependency
      - create
      - prepare
    check_sequence:
      - dependency
      - cleanup
      - destroy
      - syntax
      - create
      - prepare
      - converge
      - verify
      - cleanup
      - destroy
    converge_sequence:
      - dependency
      - create
      - prepare
      - converge
    destroy_sequence:
      - dependency
      - cleanup
      - destroy
    test_sequence:
      - dependency
      - cleanup
      - destroy
      - syntax
      - create
      - prepare
      - converge
      - idempotence
      - side_effect
      - verify
      - cleanup
      - destroy
    search_paths:
      - ${MOLECULE_PROJECT_DIRECTORY:-./molecule}
      - ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients

scenarios:
  - name: clients/geth-lighthouse
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/geth-lighthouse
  - name: clients/geth-prysm
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/geth-prysm
  - name: clients/geth-teku
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/geth-teku
  - name: clients/geth-lodestar
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/geth-lodestar
  - name: clients/reth-lighthouse
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/reth-lighthouse
  - name: clients/reth-prysm
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/reth-prysm
  - name: clients/reth-teku
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/reth-teku
  - name: clients/reth-lodestar
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/reth-lodestar
  - name: clients/reth-nimbus
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/reth-nimbus
  - name: clients/erigon-lighthouse
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/erigon-lighthouse
  - name: clients/erigon-prysm
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/erigon-prysm
  - name: clients/erigon-teku
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/erigon-teku
  - name: clients/erigon-lodestar
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/erigon-lodestar
  - name: clients/nethermind-lighthouse
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/nethermind-lighthouse
  - name: clients/nethermind-prysm
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/nethermind-prysm
  - name: clients/nethermind-teku
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/nethermind-teku
  - name: clients/nethermind-lodestar
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/nethermind-lodestar
  - name: clients/besu-lighthouse
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/besu-lighthouse
  - name: clients/besu-prysm
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/besu-prysm
  - name: clients/besu-teku
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/besu-teku
  - name: clients/besu-lodestar
    directory: ${MOLECULE_PROJECT_DIRECTORY:-./molecule}/clients/besu-lodestar
