---
- name: Deploy Validator Performance Monitoring
  hosts: all
  become: true
  vars:
    ephemery_base_dir: /root/ephemery
    metrics_dir: "{{ ephemery_base_dir }}/data/metrics"
    prometheus_dir: /prometheus
    validator_metrics_dir: "{{ prometheus_dir }}/validator-metrics"

  tasks:
    - name: Ensure required directories exist
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ ephemery_base_dir }}/scripts"
        - "{{ metrics_dir }}"
        - "{{ metrics_dir }}/history"
        - "{{ metrics_dir }}/prometheus"
        - "{{ validator_metrics_dir }}"

    - name: Copy validator performance monitoring script
      copy:
        src: ../scripts/validator_performance_monitor.sh
        dest: "{{ ephemery_base_dir }}/scripts/validator_performance_monitor.sh"
        mode: '0755'

    - name: Install required packages
      apt:
        name:
          - bc
          - curl
          - jq
        state: present
        update_cache: true

    - name: Create validator monitoring service
      template:
        src: ../ansible/templates/validator-performance-monitor.service.j2
        dest: /etc/systemd/system/validator-performance-monitor.service
        mode: '0644'

    - name: Create symbolic link for Prometheus metrics
      file:
        src: "{{ metrics_dir }}/prometheus"
        dest: "{{ validator_metrics_dir }}"
        state: link
        force: true

    - name: Reload systemd
      systemd:
        daemon_reload: true

    - name: Enable and start validator performance monitoring service
      systemd:
        name: validator-performance-monitor
        enabled: true
        state: started

    - name: Wait for metrics file to be created
      wait_for:
        path: "{{ metrics_dir }}/validator_metrics.json"
        state: present
        timeout: 120
      register: metrics_file
      ignore_errors: true

    - name: Check service status
      command: systemctl status validator-performance-monitor
      register: service_status
      changed_when: false
      ignore_errors: true

    - name: Display service status
      debug:
        var: service_status.stdout_lines

    - name: Enable and restart Prometheus container if running
      community.docker.docker_container:
        name: prometheus
        restart: true
      ignore_errors: true

    - name: Create Grafana dashboard directory
      file:
        path: "{{ ephemery_base_dir }}/dashboard/grafana/dashboards"
        state: directory
        mode: '0755'

    - name: Copy Validator Performance Dashboard to Grafana
      copy:
        src: ../dashboard/grafana/dashboards/validator_performance.json
        dest: "{{ ephemery_base_dir }}/dashboard/grafana/dashboards/validator_performance.json"
        mode: '0644'

    - name: Restart Grafana container if running
      community.docker.docker_container:
        name: grafana
        restart: true
      ignore_errors: true

    - name: Display completion message
      debug:
        msg:
          - "Validator Performance Monitoring has been deployed!"
          - "View the metrics at: http://{{ ansible_host }}:3000/d/validator-performance"
          - "View raw metrics at: {{ metrics_dir }}/validator_metrics.json"
