---
# Consolidated deployment playbook for Ephemery nodes
# This playbook deploys both execution and consensus clients

- name: Deploy Ephemery Node
  hosts: all
  become: true
  gather_facts: true
  
  vars:
    # Default client selections - can be overridden with -e parameters
    el_client_name: "geth"
    cl_client_name: "lighthouse"
    
    # Default data directory
    data_dir: "/opt/ephemery"
    
    # Default network ID
    network_id: "13337"
    chain_id: "13337"
    
    # Enable metrics by default
    enable_metrics: true
    
  pre_tasks:
    - name: Include OS-specific variables
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ ansible_distribution | lower }}.yml"
        - "{{ ansible_os_family | lower }}.yml"
        - "defaults.yml"
      tags: always
      
    - name: Display client selections
      debug:
        msg: 
          - "Deploying Ephemery node with:"
          - "Execution Client: {{ el_client_name }}"
          - "Consensus Client: {{ cl_client_name }}"
          - "Data Directory: {{ data_dir }}"
          - "Network ID: {{ network_id }}"
      tags: always
      
    - name: Validate client selections
      assert:
        that:
          - el_client_name in ['geth', 'nethermind', 'besu', 'erigon']
          - cl_client_name in ['lighthouse', 'prysm', 'teku', 'nimbus', 'lodestar']
        fail_msg: "Invalid client selection. Supported execution clients: geth, nethermind, besu, erigon. Supported consensus clients: lighthouse, prysm, teku, nimbus, lodestar."
        success_msg: "Client selections are valid"
      tags: always
      
  roles:
    - role: common
      tags: 
        - common
        
    - role: execution_client
      tags: 
        - execution
        
    - role: consensus_client
      tags: 
        - consensus
        
  post_tasks:
    - name: Wait for execution client RPC to be available
      uri:
        url: "http://localhost:8545"
        method: POST
        body_format: json
        body: '{"jsonrpc":"2.0","method":"net_version","params":[],"id":1}'
        status_code: 200
      register: el_rpc_check
      until: el_rpc_check.status == 200
      retries: 10
      delay: 5
      failed_when: false
      tags: 
        - verify
        
    - name: Display execution client status
      debug:
        msg: "Execution client {{ el_client_name }} is {{ 'running' if el_rpc_check.status == 200 else 'not responding' }}"
      tags: 
        - verify
        
    - name: Wait for consensus client API to be available
      uri:
        url: "http://localhost:5052/eth/v1/node/version"
        method: GET
        status_code: 200
      register: cl_api_check
      until: cl_api_check.status == 200
      retries: 10
      delay: 5
      failed_when: false
      tags: 
        - verify
        
    - name: Display consensus client status
      debug:
        msg: "Consensus client {{ cl_client_name }} is {{ 'running' if cl_api_check.status == 200 else 'not responding' }}"
      tags: 
        - verify
        
    - name: Display deployed Ephemery node information
      debug:
        msg:
          - "Ephemery node deployment summary:"
          - "Execution client: {{ el_client_name }} ({{ 'running' if el_rpc_check.status == 200 else 'not responding' }})"
          - "Consensus client: {{ cl_client_name }} ({{ 'running' if cl_api_check.status == 200 else 'not responding' }})"
          - "JWT secret: {{ jwt_secret_path }}"
          - "Data directory: {{ data_dir }}"
          - "Execution API: http://localhost:8545"
          - "Consensus API: http://localhost:5052"
          - "Network ID: {{ network_id }}"
      tags:
        - verify
        - summary 