---
- name: Verify
  hosts: all
  vars:
    el: erigon
    cl: lighthouse
  tasks:
    - name: Include mock services verification tasks
      ansible.builtin.include_tasks:
        file: ../../shared/verify-mock-services.yml
