---
- name: Verify
  hosts: all
  vars:
    el: besu
    cl: lodestar
  tasks:
    - name: Include mock services verification tasks
      ansible.builtin.include_tasks:
        file: ../../shared/verify-mock-services.yml
