---
# Playbook for setting up firewall rules
- name: Configure firewall
  hosts: all
  become: true
  tasks:
    - name: Firewall setup tasks
      block:
        - name: Import firewall tasks
          ansible.builtin.import_tasks:
            file: ../tasks/firewall.yaml
