---
# Playbook to update all Ephemery nodes to use genesis sync

- name: Configure local environment
  hosts: localhost
  connection: local
  become: false  # Explicitly disable sudo for localhost
  gather_facts: false
  vars:
    inventory_file: "{{ lookup('env', 'INVENTORY_FILE') | default(playbook_dir + '/../inventory.yaml') }}"
  tasks:
    - name: Check if inventory exists
      ansible.builtin.stat:
        path: "{{ inventory_file }}"
      register: inventory_stat
      delegate_to: localhost

    - name: Fail if inventory doesn't exist
      ansible.builtin.fail:
        msg: "Inventory file {{ inventory_file }} not found. Please specify a valid inventory with -e 'INVENTORY_FILE=path/to/inventory'"
      when: not inventory_stat.stat.exists

    - name: Ensure genesis sync configuration is in place
      ansible.builtin.import_tasks: ../tasks/ensure_genesis_sync.yaml

- name: Display instructions for applying changes
  hosts: localhost
  connection: local
  become: false  # Explicitly disable sudo for localhost
  gather_facts: false
  vars:
    inventory_file: "{{ lookup('env', 'INVENTORY_FILE') | default(playbook_dir + '/../inventory.yaml') }}"
  tasks:
    - name: Show next steps
      ansible.builtin.debug:
        msg: |
          Genesis sync configuration has been prepared.

          To apply these changes to your Ephemery nodes:

          1. Review the generated playbook: ansible/playbooks/switch_to_genesis_sync.yaml
          2. Run: ansible-playbook -i {{ inventory_file }} ansible/playbooks/switch_to_genesis_sync.yaml

          This will:
          - Stop the consensus client container
          - Clear the consensus client database
          - Restart the consensus client with genesis sync parameters

          Note: This process will require your nodes to resync from genesis, which may take time.
