---
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - /etc/prometheus/rules/*.yaml
  - /etc/prometheus/rules/jwt_authentication_alerts.yaml  # Include JWT authentication alerts

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - alertmanager:9093

# This Prometheus configuration uses standardized paths from /opt/ephemery/config/ephemery_paths.conf
# Configuration file paths should be updated when changing ephemery base paths

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "lighthouse"
    metrics_path: /metrics
    static_configs:
      - targets: ["ephemery-lighthouse:5054"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "lighthouse"

  - job_name: "geth"
    metrics_path: /debug/metrics/prometheus
    static_configs:
      - targets: ["ephemery-geth:6060"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "geth"

  - job_name: "node_exporter"
    static_configs:
      - targets: ['node-exporter:9100']

  - job_name: "validator-metrics"
    metrics_path: /metrics
    static_configs:
      - targets: ["localhost:8009"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: "validator"

  # JWT authentication monitoring metrics
  - job_name: 'jwt_monitoring'
    scrape_interval: 60s
    metrics_path: /metrics
    static_configs:
      - targets: ['localhost:9301']
        labels:
          instance: 'jwt_monitoring'
          component: 'auth'
