---
- name: Verify client functionality
  hosts: all
  become: true
  tasks:
    - name: Check if Nethermind container is running
      ansible.builtin.command: docker ps --filter name=ephemery-nethermind --format '{% raw %}{{.Names}}{% endraw %}'
      register: nethermind_container
      changed_when: false
      failed_when: nethermind_container.stdout == ""

    - name: Check if Teku container is running
      ansible.builtin.command: docker ps --filter name=ephemery-teku --format '{% raw %}{{.Names}}{% endraw %}'
      register: teku_container
      changed_when: false
      failed_when: teku_container.stdout == ""

    - name: Verify Nethermind API is accessible
      uri:
        url: http://localhost:8545
        method: POST
        body_format: json
        body: '{"jsonrpc":"2.0","method":"web3_clientVersion","params":[],"id":1}'
        status_code: 200
      register: nethermind_health
      failed_when: nethermind_health.status != 200 or 'Nethermind' not in nethermind_health.json.result
      changed_when: false
      ignore_errors: true  # Sometimes takes longer to start

    - name: Verify Teku API is accessible
      uri:
        url: http://localhost:5051/eth/v1/node/health
        method: GET
        status_code: 200
      register: teku_health
      failed_when: teku_health.status != 200
      changed_when: false
      ignore_errors: true  # Sometimes takes longer to start

    - name: Verify JWT authentication is working
      ansible.builtin.shell: |
        curl -s -X POST \
          -H "Content-Type: application/json" \
          --data '{"jsonrpc":"2.0","method":"engine_getPayloadV1","params":[],"id":1}' \
          http://localhost:8551
      register: jwt_check
      changed_when: false
      failed_when: '"Unauthorized" not in jwt_check.stdout'  # Should fail without JWT

    - name: Check client memory limits
      ansible.builtin.shell: |
        docker inspect ephemery-nethermind --format='{% raw %}{{.HostConfig.Memory}}{% endraw %}'
      register: nethermind_memory
      changed_when: false
      failed_when: nethermind_memory.stdout | int < 3000000000  # Should be close to 3GB

    - name: Check Teku memory limits
      ansible.builtin.shell: |
        docker inspect ephemery-teku --format='{% raw %}{{.HostConfig.Memory}}{% endraw %}'
      register: teku_memory
      changed_when: false
      failed_when: teku_memory.stdout | int < 3000000000  # Should be close to 3GB

    - name: Verify client logs for errors
      ansible.builtin.shell: |
        docker logs ephemery-nethermind 2>&1 | grep -i "error\|exception\|fatal" | wc -l
      register: error_count
      changed_when: false
      failed_when: error_count.stdout | int > 10  # Some errors during init are normal
