name: Lint

on:
  pull_request:
    branches:
      - main

jobs:

  pre-commit:
    name: pre-commit
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Cache pre-commit
        uses: actions/cache@v4
        with:
          path: ~/.cache/pre-commit
          key: pre-commit-${{ runner.os }}-py3.11-${{ hashFiles('.pre-commit-config.yaml') }}

      - name: Install ansible and dependencies
        run: |
          pip install ansible-core
          pip install ansible-lint
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          chmod +x scripts/install-collections.sh
          ./scripts/install-collections.sh

      - name: Install pre-commit
        run: pip3 install pre-commit

      - name: Run pre-commit
        run: pre-commit run --all-files --show-diff-on-failure --color always
        env:
          ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/collections

      - name: Run ansible-lint directly
        if: always()  # Run even if pre-commit fails
        run: ansible-lint
        env:
          ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/collections
