name: Molecule Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ansible-lint yamllint
      - name: Check YAML file extensions
        run: |
          chmod +x scripts/check-yaml-extensions.sh
          ./scripts/check-yaml-extensions.sh
      - name: Run ansible-lint
        run: |
          ansible-lint
      - name: Run yamllint
        run: |
          yamllint .

  molecule:
    runs-on: ubuntu-latest
    needs: lint
    strategy:
      fail-fast: false
      matrix:
        scenario:
          - default
          - validator
          # Add other critical scenarios here
          # - geth-prysm
          # - clients
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r requirements-dev.txt
          pip install molecule molecule-docker docker pytest-testinfra ansible-lint
      - name: Verify Docker
        run: |
          docker --version
          docker info
          ls -la /var/run/docker.sock
      - name: Update Molecule configuration for GitHub Actions
        run: |
          for file in $(find molecule -name "molecule.yml"); do
            echo "Updating $file for GitHub Actions environment..."
            # Use default Docker socket path for GitHub Actions
            sed -i 's|/Users/.*/\.docker/run/docker\.sock|/var/run/docker.sock|g' $file
            # Ensure proper cgroup mounting
            sed -i 's|/sys/fs/cgroup:/sys/fs/cgroup:ro|/sys/fs/cgroup:/sys/fs/cgroup:rw|g' $file
            # Add cgroupns_mode if not present
            if ! grep -q "cgroupns_mode:" $file; then
              sed -i '/command:/a\    cgroupns_mode: host' $file
            fi
          done
      - name: Run Molecule tests for ${{ matrix.scenario }} scenario
        run: molecule test -s ${{ matrix.scenario }}
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          DOCKER_HOST: unix:///var/run/docker.sock
      - name: Archive test results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: molecule-${{ matrix.scenario }}-results
          path: |
            **/molecule/${{ matrix.scenario }}/*-result.xml
            **/molecule/${{ matrix.scenario }}/logs/
          retention-days: 7
